### ISSUE TITLE
Make it possible to chose which sub-fields of the related collection we should keep

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#112]
## Problem

If you have a collection in Strapi that has a relation with another collection, once you index it to MeiliSearch the output is the following: 

```json
 {
    "id": 2,
    "name": "Italian",
    "restaurants": [
      {
        "id": 1,
        "name": "PetitPatapon",
        "description": "Delicieux",
        "created_by": 1,
        "updated_by": 1,
        "created_at": "2021-03-03T12:09:10.979Z",
        "updated_at": "2021-03-03T12:09:10.988Z"
      },
      {
        "id": 2,
        "name": "LaLoLaLiTa",
        "description": "Ma que bello",
        "created_by": 1,
        "updated_by": 1,
        "created_at": "2021-03-03T12:17:46.503Z",
        "updated_at": "2021-03-03T12:17:46.515Z"
      }
    ]
  },
```

But for MeiliSearch to create [facets](https://docs.meilisearch.com/reference/features/faceted_search.html) the best way would be to transform the restaurants object into the following:

```json
 {
    "id": 2,
    "name": "Italian",
    "restaurants": ["LaLoLaLiTa", "PetitPatapon"]
 },
```

## Solution

It would be better that on indexation, if a relation is discovered, the user is prompted to chose one field or to ignore the questions.

**Comment by taker93** [comment]
In the meantime: What are options to have facets work for anything like that?

**Comment by taker93** [comment]
Ok, so for now I found a workaround to make facets on relations work:

When you've created your post types go to your strapi `/api/<CONTENT_TYPE>` folder. In there your should find 4 folders:

- `config`
- `controllers`
- `models`
- `services`

Go to the `services` folder and open your `posts.js`.

In there you can customize how posts are read from the database. As the meilisearch plugin is using the `find()`-Method of your types service, you need to overwrite its functionality like the following:

```javascript
"use strict";

/**
 * Read the documentation (https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#core-services)
 * to customize this service
 */

// use lodash as it is inherited by strapi itself
const _ = require("lodash");

module.exports = {
  /**
   * Retrieve records.
   *
   * @return {Array}
   */
  async find(params, populate) {
    return strapi
      .query("restaurant")
      .find(params, populate)
      .then((entities) => {
        return entities.map((entity) => {
          // check if relation is present
          if (entity.categories) {
            // flatten relation array with lodash
            // "key" is the key you want to represent the category for meilisearch-facets
            // if you do not want to override the standard field "categories" just change entity.categories to something else
            entity.categories = _.map(_.flatten(entity.categories), "key");
          }
          return entity;
        });
      });
  },
};
```

More on customizing your backend:
https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html

I think this functionality (lodash and flattening) could be the way for the meilisearch-plugin to provide such functionality as long multi-dimensional searches are not possible by meilisearch itself.

Plugin needs to be changed that it recognizes that the content-type you want to add to meilisearch has relations on other types. Therefor it should be possible to have an UI-PopUp which shows all fields of the type. In there you could choose which fields you want to add to the index. Besides choosing the fields you could override the keys and transformation. Transformation: Use-Cases are Enums and relations. Relations could be flattened to one field, Enums mapped to another value.

**Comment by ablaas** [comment]
This is a very interesting improvement.
Usually, categories, tags, or other structured content will come from relationships, and being able to add to the index those fields as facets gives us lightnin' fast filtering over the collections, without the hassle of creating nested GraphQL queries

**Comment by ablaas** [comment]
> Ok, so for now I found a workaround to make facets on relations work:
> 
> When you've created your post types go to your strapi `/api/<CONTENT_TYPE>` folder. In there your should find 4 folders:
> 
> * `config`
> * `controllers`
> * `models`
> * `services`
> 
> Go to the `services` folder and open your `posts.js`.
> 
> In there you can customize how posts are read from the database. As the meilisearch plugin is using the `find()`-Method of your types service, you need to overwrite its functionality like the following:
> 
> ```js
> "use strict";
> 
> /**
>  * Read the documentation (https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#core-services)
>  * to customize this service
>  */
> 
> // use lodash as it is inherited by strapi itself
> const _ = require("lodash");
> 
> module.exports = {
>   /**
>    * Retrieve records.
>    *
>    * @return {Array}
>    */
>   async find(params, populate) {
>     return strapi
>       .query("restaurant")
>       .find(params, populate)
>       .then((entities) => {
>         return entities.map((entity) => {
>           // check if relation is present
>           if (entity.categories) {
>             // flatten relation array with lodash
>             // "key" is the key you want to represent the category for meilisearch-facets
>             // if you do not want to override the standard field "categories" just change entity.categories to something else
>             entity.categories = _.map(_.flatten(entity.categories), "key");
>           }
>           return entity;
>         });
>       });
>   },
> };
> ```
> 
> More on customizing your backend:
> https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html
> 
> I think this functionality (lodash and flattening) could be the way for the meilisearch-plugin to provide such functionality as long multi-dimensional searches are not possible by meilisearch itself.
> 
> Plugin needs to be changed that it recognizes that the content-type you want to add to meilisearch has relations on other types. Therefor it should be possible to have an UI-PopUp which shows all fields of the type. In there you could choose which fields you want to add to the index. Besides choosing the fields you could override the keys and transformation. Transformation: Use-Cases are Enums and relations. Relations could be flattened to one field, Enums mapped to another value.

Great workaround... thanks @taker93 !!!!

**Comment by harish2704** [comment]
I think #265 is related to this
