### ISSUE TITLE
Meilisearch can't work with Strapi single type content

### ISSUE THREAD

**Issue by VivianSolide** [meilisearch/strapi-plugin-meilisearch#122]
```
node v14.16.0
strapi v3.5.4
strapi-plugin-meilisearch v0.2.0
ubuntu v20.04
```

Hi there,

I spotted an issue inside numberOfRowsInCollection function.
Indeed, I get `strapi.services[collection].count is not a function`
But if I the function returns 1 it works.

The problem comes from Strapi single type content.
In my case, I had an Home Page single type content.
Once removed, it's perfectly fine.

It's only because, you can't count on a Strapi single type content.

Nevertheless, Meilisearch doesn't should fetch this kind of "collection".

**Comment by bidoubiwa** [comment]
@VivianSolide thanks a lot for reporting this issue. 
I will definitely try it out.
