### ISSUE TITLE
How to handle single types 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#124]
Appart from `Collection types` in Strapi, that acts as a SQL table with many rows, there are also `single types`. 

Collection types are added straightforwardly to MeiliSearch as we just index all rows. 
But single types are only composed of one element. 

The use case of single types are mostly content manager if I understand correctly. Meaning that one type represent the content of one element. 

We could go in three directions with this: 

### 1. Ignore single types
Speaks for itself

### 2. Accept one single type to be indexed in one index
This option does not make sense but could be useful in some rare use cases

### 3. Index all singles type in the same `single-types` index.  
Because single types are content managers, we might want to index them all together. 
If the use case is indeed that, it would make it possible for users to search inside all content types at once, and thus create a search experience on the content of the website rather than on the products stored in collecrtions

**Comment by tvvignesh** [comment]
I have the same need as well. I am able to index the collection types properly without any issues but need a way to index single types as well. Any help appreciated.

**Comment by bidoubiwa** [comment]
Hey @tvvignesh, what do you think would be the best option amongst the one mentioned above ?

**Comment by tvvignesh** [comment]
@bidoubiwa I guess option 3 would make sense for single types considering they can all be grouped together, but 2 should work as well.

As long as I can access the index and get the data, it shouldn't be an issue.

**Comment by Tocas97** [comment]
Hey everyone!

This use case is not urgent for me, though it will be handy when I get around to implementing full website search on a project I'm working on, but I just wanted to chime in a little bit. I think the solution that could potentially avoid any future problems or incompatibility with other plugins would be to treat single types the same as collection types. 
Even Strapi itself (at least in 3.6.8) even has a dedicated table for each of the single types leading me to believe that the single entry per content type restriction itself is implemented in the API and not at the data base level. This allows plugin creators to have more freedom and do stuff like the [content versioning plugin](https://github.com/notum-cz/strapi-plugin-content-versioning) which allows an entry to have multiple drafts (if this is currently enabled for single content types, I don't know but it would certainly be possible).
But an even more practical example would be the official i18n plugin, which actually creates multiple entries (one per each locale).
![image](https://user-images.githubusercontent.com/46816435/154119173-93a0e1eb-5472-4fad-bd2b-bc544b9360ea.png)

Hope I was helpful 😊
