### ISSUE TITLE
MeiliSearchApiError: request , it doesn't matter whether or not a "masterKey" is passed.

### ISSUE THREAD

**Issue by LucasSToledo** [meilisearch/strapi-plugin-meilisearch#176]
Bug when trying to update a collection after configuring MeiliSearch.
It doesn't matter whether or not I create a "masterKey". The error "Could not connect with MeiliSearch ECONNREFUSED" is always returned.

How to reproduce. Run MeiliSearch passing parameter "MEILI_MASTER_KEY=masterKey" in development environment. When trying to add the collections to index the error mentioned above is reported.

It was tried to run without passing the "masterKey" information so that there was no restriction and even so the same access error was reported.
![Screenshot from 2021-06-01 17-10-34](https://user-images.githubusercontent.com/2990345/120384260-4cbe0200-c2fc-11eb-9a1b-5a4d0caa7212.png)

**Comment by bidoubiwa** [comment]
Hello @LucasSToledo 
It does not seem to come from the `masterKey` but from the instance of meilisearch. On what address is your meilisearch running?

**Comment by LucasSToledo** [comment]
Hi @bidoubiwa , You're right!
I was running on docker and forgot to associated the network between the services. Thank you.

**Comment by bidoubiwa** [comment]
I'm happy it solved the problem :)
