### ISSUE TITLE
[Discussion/Proposal] Make strapi-plugin-meilisearch client agnostic (ie: strapi-plugin-search)

### ISSUE THREAD

**Issue by ghassanachi** [meilisearch/strapi-plugin-meilisearch#192]
I'm currently working on a Strapi project that requires search-engine integration. My initial plan was to go with Meilisearch, but unfortunately  the project is heavily dependent on GeoLocation queries. I am thinking of turning to Typesense for now before switching back to Meilisearch when GeoLocation queries are added. 

With that in mind I was a little sad to find out that there were no Typesense-Strapi plugins, and I was contemplating a couple different options.

1. Registering the Typesense client into Strapi using a hook and then simply using it in the model lifecycles. This is the simplest solution, but its also the most limited. 
2. Clone this repository, and make the necessary modifications to make it work with the Typesense client.
 
It's while considering option 2. and taking a look at the code in this repo that the thought of a client agnostic search plugin came to me.  Below is a description of what I have in mind.

## Description

Make this project client agnostic in a way that is similar to the "Strapi Upload Plugin" where the choice of provider is open to the end-user and is as simple as installing an additional dependency and modifying your config. 

This would also be similar to the way [instantsearch.js](https://github.com/algolia/instantsearch.js/) package works were the client can be interchanged based on what backend service you are using ([instant-meilisearch](https://github.com/meilisearch/instant-meilisearch), [typesense-instantsearch-adapter]( https://github.com/typesense/typesense-instantsearch-adapter), etc...).

## Rational

Meilisearch has the best search-engine Strapi integration, and making this project client agnostic would create a more robust Strapi ecosystem where this would be the go to "Search Plugin". And as the maintainers of the projects this could also be good exposure for Meilisearch.

## Implementation

From what I could tell going through the code (relatively quickly, so sorry if I missed anything) most of the codebase is already client agnostic thanks for the abstraction of the http  client in the services folder. There are a couple other instances of the code being "Meilisearch" specific (Error's and credentials handling), but these should be relatively easy to abstract as well.

And for third party client integration, this plugin would handle loading the client and reading the config, and we could provide an API spec that all third-party clients should meet.

--- 

Sorry for the block of text, but I just wanted to get my thoughts down on the paper. And hoping to open a discussion on the topic.

**Comment by bidoubiwa** [comment]
Hello @ghassanachi thanks so much for taking time to develop your idea and for you very kind words. I think your initiative is very good but it does raise some problems: 

- The plugin has `meilisearch` written on it so it's already not agnostic in its name
- The plugin would gain in complexity if it has to be configurated by the users. Whereas today you don't need configuration. 
- The plugin still needs a big refactor to make it work. 

The maintaining could indeed bring a lot of exposures to MeiliSearch but we also have a lot of other plugins to maintain and to come and we only have so much hands. 

Nonetheless, feel free to fork this project and and develop this project as I think it is a very cool idea. I would enjoy contributing to it :)

**Comment by ghassanachi** [comment]
Thanks for the prompt reply. 

I'm not sure I'll have the time in the upcoming weeks to work on the refactor, but if/when I do I'll make sure to let you know. 

Thanks again for all the great work, on this project and Meilisearch in general.

I'll leave it up to you to close this issue.
