### ISSUE TITLE
Multi index search with Strapi and Meilisearch

### ISSUE THREAD

**Issue by tvvignesh** [meilisearch/strapi-plugin-meilisearch#193]
**Description**
Hi 👋🏼 I have been using Strapi for some time now and am currently working on integrating `strapi-plugin-meilisearch` to implement Search in the website.

While I am able to get it working with React Instantsearch and Strapi, I see that every collection becomes its own index so to do a search across multiple collections if I want to implement a global search, I have to implement a multi-index search and I did follow these repos for the same with multiple `<Index>`

https://github.com/algolia/doc-code-samples/blob/master/React%20InstantSearch/multi-index-hits/src/App.js

https://github.com/algolia/react-instantsearch/tree/7520e893bbec8816f6e283438610ad845616b0b4/examples/multi-index

But still I see instantsearch searching only a single index as specified within <InstantSearch> (in this case `stores`) - any ideas why? I do see that search is working when I try calling the API directly via `curl`

Using
"react-instantsearch-dom": "^6.11.1",
"@meilisearch/instant-meilisearch": "^0.5.0",

And this is how the snippet looks like.. The syntax seems to be correct but not sure why multi-index search doesn't work..

![image](https://user-images.githubusercontent.com/1165845/123533237-4d965800-d731-11eb-8ed5-fa4c7fb6fea9.png)

![image](https://user-images.githubusercontent.com/1165845/123533299-bbdb1a80-d731-11eb-89f0-dbb5bd28aa31.png)

**Expected behavior**
Multi index search works with React instantsearch

**Current behavior**
No hit fired during search

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
"react-instantsearch-dom": "^6.11.1",
"@meilisearch/instant-meilisearch": "^0.5.0",

**Comment by liamb13** [comment]
At this stage, it's currently not possible with MeiliSearch: https://roadmap.meilisearch.com/c/74-multi-index-search

Until implemented, the only thing I could think that might be worthwhile is to merge all strapi collections into a single meilisearch index.

**Comment by bidoubiwa** [comment]
@liamb13 could you make an appart issue suggesting this solution?

**Comment by tvvignesh** [comment]
@liamb13 Thanks for letting me know. Regarding merging them all to a single index, can you point me to a reference for the same? I am not sure how to do that considering Meilisearch creates separate index for every collection by default.

**Comment by liamb13** [comment]
@tvvignesh, a good friend and developer @mattiebelt just created the following: https://github.com/MattieBelt/strapi-plugin-meilisearch

Thus far, I haven't had much time to play but it's working well for me at this stage!

![image](https://user-images.githubusercontent.com/69778531/125477920-64338131-cda2-460d-8eea-212878500204.png)

The above is searching across 3 Strapi collections:
- Articles
- Resources
- Tools

**Comment by harish2704** [comment]
PR #265 can also allow composite index
