### ISSUE TITLE
Timestamps in search

### ISSUE THREAD

**Issue by anatintescu** [meilisearch/strapi-plugin-meilisearch#218]
Hi all! I've just integrated strapi-plugin-meilisearch "^0.3.2" in my blog app (with fe in NextJs; in FE I use"meilisearch": "^0.19.0").  I want to impleement the search in my Article entity. Is there a way I can make the search method return also the auto-generated timestamps from Strapi (created_at, published_at)? I tried to specify these fields in the displayedAttributes , but it doesn't work. Thanks!

**Comment by bidoubiwa** [comment]
It is absolutely possible. They are voluntarily removed because I thought they would not be necessary.

**Comment by atintescu** [comment]
@bidoubiwa ,could you help me add them?

**Comment by CaroFG** [comment]
Hi! I've had feedback from users who want to be able to use the sortBy with these fields, maybe we should consider transforming those fields into timestamps too? WDYT?

@atintescu from what I see, all the logic is in the `./services/http.js` file  🙂

**Comment by bidoubiwa** [comment]
(sorry I was on vacation)

> Hi! I've had feedback from users who want to be able to use the sortBy with the created_at, updated_at and published_at fields, maybe we should consider transforming those fields into timestamps too? WDYT?

I don't think it is a good idea to change the format of the data before sending it to MeiliSearch. User's might want to keep it in their original form. A solution to that is the user creating its own `created_at_timestamp` where he converts `created_at` when it is being updated. This is possible using [lifecycles hooks](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#available-lifecycle-hooks).


@anatintescu About the PR requests, to make the changes you should remove the following lines from `http.js`

```js
// remove the whole function
function removeDateLogs(document) {
  const {
    updated_at: omitUpdatedAt,
    created_at: omitCreatedAt,
    created_by: omitCreatedBy,
    updated_by: omitUpdatedBy,
    published_at: omitPublishedAt,
    ...noDateLogDocument
  } = document
  return noDateLogDocument 
}

async function addDocuments({ indexUid, data }) {
  const noDateLogDocuments = data.map(document => removeDateLogs(document)) // remove
  return this.client.index(indexUid).addDocuments(noDateLogDocuments)
}
```

For the other parts of the contribution: making the `pr`, etc.. here is a [guide on how to do so](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/CONTRIBUTING.md#how-to-contribute) 😊.

If you have any question about how to contribute feel free to come and talk to me on our [slack](https://docs.meilisearch.com/) (link is in the upper right part of the docs).

**Comment by harish2704** [comment]
PR #265 allow us to take full control over what is to be sent to search engine for indexing . 
This way , we can address these kind of issues without changing hard-coded default behavior
