### ISSUE TITLE
Need to add facets settings through the plugin

### ISSUE THREAD

**Issue by mgaviola1** [meilisearch/strapi-plugin-meilisearch#219]
Hi, it would be great if you could add a setting to add facets to the meilisearch instance, right now if I'm using the plugin there's no way to define them and I have to add them through cURL or other language.

**Comment by paulpopus** [comment]
@bidoubiwa In the meantime, is there a recommended programmatic way to do this, even if its patching the plugin? Or is CLI the best option?

**Comment by bidoubiwa** [comment]
Hey! @paulpopus you can create a script with meilisearch-js do add them: [this example](https://github.com/meilisearch/meilisearch-js/blob/main/tests/env/node/getting_started.js) should cover what you need.

**Comment by bidoubiwa** [comment]
fixed by #329
