### ISSUE TITLE
Add the release drafter

### ISSUE THREAD

**Issue by curquiza** [meilisearch/strapi-plugin-meilisearch#24]
https://github.com/meilisearch/integration-guides/blob/main/guides/release-drafter.md
This would be helpful in managing the changelogs

**Comment by bidoubiwa** [comment]
I could add the release drafter without having a package manager I suppose?

**Comment by curquiza** [comment]
Yes, it is only to make the draft of the GitHub release :) Nothing else

**Comment by bidoubiwa** [comment]
Should we start before there is a working version?

**Comment by curquiza** [comment]
No, this is one of the final steps I think ;)
