### ISSUE TITLE
Sanitize the field to remove html tags before saving for search.

### ISSUE THREAD

**Issue by PixeledCode** [meilisearch/strapi-plugin-meilisearch#249]
**Description**
Currently for people using CKEditor, using Meilisearch creates a lot of html tags in Meilisearch result as well. That's not really ideal and creates a lot of issues when using other Meilisearch features like crop etc.

**Basic example**
In my current project, I'm using CkEditor as rich text content editor but it outputs html tags which although is great for my usecase, creates a lot of problems for Meilisearch. 

**Other**
One solution I could think of is basically sanitize the content that Meilisearch scarps before saving. Or maybe saving multiple fields.

**Comment by harish2704** [comment]
Hi All, PR #265 addresses this issue
