### ISSUE TITLE
API Key Label in Strapi Admin should be improved to avoid confusion

### ISSUE THREAD

**Issue by ablaas** [meilisearch/strapi-plugin-meilisearch#279]
**Description**
The actual KEY label in the Meilisearch Plugin Admin page is a bit confusing, as it reads: "API Key".
This is the Meili MASTER KEY, so it should be handled with care.

To avoid confusion, I suggest to improve the label to reflect the importance of this key.
It should also alert that this is the MASTER Key for Meili and must NOT be used in frontends or meili-strapi clients.

Also, the actual documentation should explain better the differences between the keys and maybe a link to the documentation where Authentication for Meilisearch is explained: [https://docs.meilisearch.com/reference/features/authentication.html](https://docs.meilisearch.com/reference/features/authentication.html)

**Nice to have (idea)**
It would be great if you could see the 3 keys in the plugin, once inserted the master Key

- Master key (obfuscated and a button to show it)

A button to FETCH:
- Primary key (obfuscated and a button to show it)
- Public key (plain text)

**Screenshots or Logs**
Actual documentation:
![image](https://user-images.githubusercontent.com/5245751/137157472-f63968ae-ee8e-4a4c-a4fa-a5e317cc6da7.png)

Actual Strapi Admin Plugin configuration
![image](https://user-images.githubusercontent.com/5245751/137157615-aff64cca-0c6b-456d-b578-a3471e38f474.png)

**Environment (please complete the following information):**
- OS: Linux on RedHat Openshift pods
- MeiliSearch version: v.0.22.0
- strapi-plugin-meilisearch version: v0.3.3
- Strapi version: v3.6.6

**Comment by bidoubiwa** [comment]
Hey @ablaas i made the PR to fix this https://github.com/meilisearch/strapi-plugin-meilisearch/pull/320 do you think it is more clear now?

**Comment by ablaas** [comment]
> Hey @ablaas i made the PR to fix this #320 do you think it is more clear now?

Nice!!!! Let's see it in PROD soon ;) 
Thanks @bidoubiwa
