### ISSUE TITLE
Change all outdated documentation links 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#310]
⚠️ Only once #288 has been merged

A lot of files have headers to Strapi documentation pages. A lot of them are obsolete. 

Example:
```
 * Read the documentation (https://strapi.io/documentation/developer-docs/latest/concepts/models.html#lifecycle-hooks)
```

They should either be removed or updated with correct urls.

**Comment by trantran199** [comment]
can I try it? can you guide me?

**Comment by bidoubiwa** [comment]
Hello @trantran199 
A lot of the files in the repository have a comment at the top of the file with the documentation about the related topic. For example in: https://github.com/meilisearch/strapi-plugin-meilisearch/blob/843aa801a675879dac0f8a7bd5bd15be765d0f77/config/functions/bootstrap.js

```
/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#bootstrap
 */
```

They should be checked because a lot of them are dead links. Using the current [doc of strapi](https://strapi.io/documentation/developer-docs/latest/getting-started/introduction.html), we should find the new link to the documentation and replaced the dead link in all files. 

So the above example should become: 

```
/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#functions
 */
```

But, as per the update in the body, I would prefer we wait for this pr #288 to be merged before we start doing that.
