### ISSUE TITLE
Extend the meilisearch object with MeiliSearch settings

### ISSUE THREAD

**Issue by haye-webbio** [meilisearch/strapi-plugin-meilisearch#327]
**Description**
Currently it is only possible to change the MeiliSearch settings of an index by making an API request to MeiliSearch after a collection type is indexed. It would be nice to extend the MeiliSearch object that was added with the 0.4.0 release with optional [MeiliSearch settings](https://docs.meilisearch.com/reference/features/settings.html).

**Basic example**
With the 0.4.0 release it is now possible to transform the content-types before inserting them into MeiliSearch by using the following code. 

```javascript
module.exports = {
  meilisearch: {
    transformEntry({ entry, model }) {
      return sanitizeEntity(entry, { model })
    },
  },
}
```

By adding a settings property it would be possible to update the MeiliSearch settings after a content type gets indexed. For example:

```javascript
module.exports = {
  meilisearch: {
    transformEntry({ entry, model }) {
      return sanitizeEntity(entry, { model })
    },
    settings: {
      rankingRules: ['typo', 'words', 'proximity', 'attribute', 'wordsPosition', 'exactness', 'desc(release_date)'],
      filterableAttributes: ['genres'],
      distinctAttribute: null,
      searchableAttributes: ['title', 'description', 'genres'],
      displayedAttributes: ['title', 'description', 'genre', 'release_date'],
      stopWords: null,
      synonyms: {
        wolverine: ['xmen', 'logan'],
        logan: ['wolverine', 'xmen']
      }
    }
  },
}
```

**Comment by bidoubiwa** [comment]
Hey @haye-webbio, if you are willing to contribute it shouln'd be to hard to add: 

- Create a function in the `collection` connector called `getSettings` 
- The same way as the function `getIndexName`, get the `settings` from the config file
- [In this line](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/connectors/meilisearch/index.js#L281), fetch the settings with `const settings = collectionConnector.getSettings()`
- make a call to MeiliSearch `await client.index(indexUid).updateSettings(settings)`

And it is done :)

**Comment by haye-webbio** [comment]
Sure! :)
