### ISSUE TITLE
How to filter document before sending to MeiliSearch?

### ISSUE THREAD

**Issue by tention** [meilisearch/strapi-plugin-meilisearch#334]
Currently the plugin will sync every single records to MeiliSearch by default. How do we limit or exclude certain document from sending to MeiliSearch?

For example I want to exclude all document from a collection type "book" with the column status of "deleted" from getting indexed.

Thanks

**Comment by bidoubiwa** [comment]
Hello @tention ! We should create another method similar to [`transformEntry`](https://github.com/meilisearch/strapi-plugin-meilisearch#transform-sent-data) that does not sanitize the content of the entries but give the possibility to filter some documents out.  It should be named `filterEntry` (or other if a better idea is suggested).

For the implementation we can reproduce the same as the one of `transformEntry`

`transformEntry` method ([example](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/resources/entries-transformers/remove-fields.js)) is taken from the config file and [used in the transformEntries method] (https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/connectors/collection.js#L132).
`transformEntries` is called in [`addCollectionInMeiliSearch ` function here](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/d78e8bb7d3f98a085995808450cd3561593674d4/connectors/meilisearch/index.js#L277) (and also another one above).

Following this implementation of `transformEntry`, `filterEntry` should not be hard to implement and should be used the same way as the standard javascript array [`.filter()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter). 

Example of usage
```js
module.exports = {
  meilisearch: {
    filterEntry({ entry }) {
      return entry.role === 'admin'
    },
  },
}
```

**Comment by nka-joel** [comment]
This whould be a great feature. Any updates on this?

**Comment by bidoubiwa** [comment]
Hello! It is already added in the v4 migration. Which comes out this week!
