### ISSUE TITLE
Incorrect `config/plugins.js` example

### ISSUE THREAD

**Issue by v4dkou** [meilisearch/strapi-plugin-meilisearch#335]
The JS `meilisearch` library expects the API Key to be provided in camelCase.
However, the configuration object in the sample uses snake_case.

```
module.exports = () => ({
  //...
  meilisearch: {
    // Your meili host
    host: "http://localhost:7700",
    // Your master key or private key
    api_key: "masterKey",
  }
  //...
})
```

Tripped me up, as after following the tutorial I got the "MeiliSearchApiError: The X-MEILI-API-KEY header is missing." error.
Done some digging around to see what went wrong and found that this configuration object goes straight to `meilisearch` library, so it should be configured like it says in the docs over there.

I guess this is also worth mentioning just in case configuration becomes more advanced, so as to point people to the right direction from the start, but this is out of scope for my PR.

P.S. Great project overall :heart:

**Comment by bidoubiwa** [comment]
Thanks a lot for raising and fixing this issue 🔥
