### ISSUE TITLE
MeilliSearchTimeOutError: timeout 5000ms exceeded on process

### ISSUE THREAD

**Issue by davidho8087** [meilisearch/strapi-plugin-meilisearch#337]
Hi guys. I got this error while creating 150K documents for indexing.
 
[MeilliSearchTimeOutError ]: timeout of 5000ms has exceeded on process 201 when waiting for pending update to resolve. 

May I know how to solve this issue? 
What settings / attributes and filename should I look into for code changes / customization?

Thanks.

![image](https://user-images.githubusercontent.com/12009185/148482475-65260650-f6e5-4b15-9e84-ede7dd4c8e89.png)

**Comment by bidoubiwa** [comment]
Hello @davidho8087 
Unfortunately when the dataset is to big my function doesn't handle well the long waiting times. A quick solution should be to improve the timeout. Meanwhile, your documents should still be indexed correctly. Is it the case?

**Comment by davidho8087** [comment]
Thanks for the reply, yes, indeed indexed correctly. however it is quick slow to perform indexing. 

![image](https://user-images.githubusercontent.com/12009185/151492553-2aa5c428-82b3-4485-b2f7-bcb8224a6775.png)

**Comment by bidoubiwa** [comment]
Hey @davidho8087 
The indexation time is something our team is working on. It is planned for the next months to make indexation faster!

**Comment by bidoubiwa** [comment]
Hey @davidho8087 
Just a small update after talking with a team member. A reason why the indexation is very slow is that the documents are sent one by one. How did you add the documents? Did you click on the checkbox or did you add the documents one by one into strapi using their own API? Knowing how it happens might help improve the script if possible 

For the faster indexation, it will be because a auto-batching system is going to be implemented. It automatically batch the small tasks to avoid having to process multiple task of small sizes in a separate task.  You can learn more [about it here](https://github.com/meilisearch/specifications/pull/96).

**Comment by davidho8087** [comment]
> Hey @davidho8087 Just a small update after talking with a team member. A reason why the indexation is very slow is that the documents are sent one by one. How did you add the documents? Did you click on the checkbox or did you add the documents one by one into strapi using their own API? Knowing how it happens might help improve the script if possible
> 
> For the faster indexation, it will be because a auto-batching system is going to be implemented. It automatically batch the small tasks to avoid having to process multiple task of small sizes in a separate task.  You can learn more [about it here](https://github.com/meilisearch/specifications/pull/96).

**Comment by davidho8087** [comment]
Hi @bidoubiwa 
Thanks for prompt response.  Here is my finding and hope your team make this plugin amazing.


**1) Real Time POST Request ( 10 documents per sec for 40K documents )** 
I did click the checkbox with listener ( Active ) from zero records and performed a stress test by pumping Post Request of 10 documents per seconds.  

FYI , Here is the gap result. 

**Beginning**
![MeiliStart](https://user-images.githubusercontent.com/12009185/153198375-894053e2-6c87-4281-9902-655aebb07f6e.jpg)

**Ended**.
![MeiliEnd](https://user-images.githubusercontent.com/12009185/153198710-87fbd0aa-2dcc-4ac6-8b97-717cc52b3df4.jpg)

2) **Bulk Indexing with 100K documents in dbase**
 - Indexing automatically stopped around 60K ++ even I tried a few attempts
 - 
 Here is the result .
 **Beginning**.. 
 
![Meili1](https://user-images.githubusercontent.com/12009185/153199255-105dad92-1bae-4d0b-a898-62054b0803e5.jpg)

**Ended**
 
![Meili2](https://user-images.githubusercontent.com/12009185/153199326-14314bd0-edc5-4546-b832-3e36b0c61f85.jpg)

![Meili3](https://user-images.githubusercontent.com/12009185/153199668-6a5b37af-ad7f-447d-8d23-2084545ba0c1.jpg)
