### ISSUE TITLE
Data indexed by lifecycle subscription depends on population and field settings of request

### ISSUE THREAD

**Issue by sargreal** [meilisearch/strapi-plugin-meilisearch#376]
**Description**
The lifecycle subscription is called with the exact data that is requested by the user. Currently, this is also exactly the data that is indexed. So if a user creates an entry with default population settings (none), no fields are populated in the data that is indexed. Also when the user manually selects the fields that he wants in the response, the other fields will also not be included in the indexed data.

**Expected behavior**
Every entry that is indexed should have the same fields and population.

**Current behavior**
Fields are only populated when adding the content type and also possibly some fields are missing when entries are added or updated through the lifecycles

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Manjaro 
- MeiliSearch version: v0.26.1
- strapi-plugin-meilisearch version: v0.6.2
- Browser: 
- Strapi version: v4.1.7

**Comment by bidoubiwa** [comment]
Hey @sargreal thanks for your issue :) I will be looking into this bug very soon.

**Comment by bidoubiwa** [comment]
Hey, @sargreal I'm coming back to this issue and I'm not sure I clearly understand what is happening. 

> The lifecycle subscription is called with the exact data that is requested by the user

What do you mean, the data that is requested? The hooks only triggers on update/delete/creation


And what is population?

If you can give me a step by step way to observe the issue that would be fantastic!

**Comment by sargreal** [comment]
Hey @bidoubiwa 

When creating/updating or deleting an entry in strapi, one always gets the entry as a result (See for example [Create an entry with REST](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#create-an-entry)). 

This returned data is the same data that passes through the lifecycle methods (just not with the id / attributes layout). Modifying which data is returned can be done using [the `population` and `fields` parameters](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#field-selection)

So as a result, which data of an entity that is submitted for indexing by this plugin in the lifecycle hooks is depends on the `population` and `fields` selection of the user.

This is probably not wanted, since in indexing the content in batches, the population and fields are both set as `*` 
https://github.com/meilisearch/strapi-plugin-meilisearch/blob/6e9e0a6809ccd28fbf280cfeef3a7a2a900255aa/server/services/content-types/content-types.js#L138-L145

-----

To observe the issue, the easiest way would be:
- Create a content type with relations and/or components
- Create some entities
- Hook the content type with the meilisearch plugin
- :heavy_check_mark: See that the entities in the meilisearch dev-frontend have the relations and/or components included
- Create some more entities using the admin panel
- :heavy_check_mark: See that these entities also have the relations and/or components included (because the admin panel always uses deep population in creation/update)
- Create some entities using the **REST-API** / **GraphQL-API** (even more interesting, since one always specifies the fields there) / **entityService** with no specific `population` and `fields` settings (but also some relations or components in the input data)
- :x: See that these do not include the related fields and/or components

-----

### Proposed fix

The entry (or entries in the case of #396 being at some point possible) in the database would need to be fetched again with the appropriate `fields` and `population` settings in the indexing process. Probably directly in the lifecycles, but asynchronously so the answer is not delayed.

-----

_Also, just as a side note and a possible performance improvement, it might be interesting to let the user also configure the default `fields` and `population` for each content type in the plugin configuration. This would fix the following problems_
- _Always needing to manually prune the unwanted fields and populations in `transformEntry`_
- _Allowing for deep population (even just two layers of components) without having to do more database requests in `transformEntry`_

**Comment by nhvu1988** [comment]
@sargreal @bidoubiwa I have the same issue so have fixed it in PR #410, could you please help to check and give a comment? Thank you!

**Comment by bidoubiwa** [comment]
Hey @paulpopus could you create a new issue with your request of settings?
