### ISSUE TITLE
Command "strapi build" does not work

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/strapi-plugin-meilisearch#385]
In the README: the command `strapi build` returns `strapi: command not found`.  Replace it with `npm run build` or `yarn build`

**Comment by bidoubiwa** [comment]
To make `strapi build` work strapi should be installed globally in your environment. Wich I did not explain in the README.md. 
By default, I think a strapi app has the `npm run build` command which uses the local Strapi. 

Could you try this one out?

**Comment by CaroFG** [comment]
`npm run build` works perfectly fine
