### ISSUE TITLE
Change `transformEntry` function in `plugin.js` to async

### ISSUE THREAD

**Issue by dzcpy** [meilisearch/strapi-plugin-meilisearch#386]
**Description**
As per documentation, currently `transformEntry` can handle all fields within a content which is neat. Howevrer `entry` doesn't contain any fields of it's relation fields' relations. Like for example if there is a multi-level category and I want to get each sub-categories it belongs to, then it's quite difficult. What about changing the `transformEntry` a bit, so it can load async calls to the database?
```js
// config/plugins.js

module.exports = {
  meilisearch: {
    config: {
      restaurant: {
        transformEntry({ entry }) {
          return {
            ...entry,
            categories: entry.categories.map(category => category.name)
          }
        },
      }
    }
  },
}
```

**Basic example**
```js
// config/plugins.js

module.exports = {
  meilisearch: {
    config: {
      restaurant: {
        async transformEntry({ entry }) {
          return {
            ...entry,
            categories: entry.categories.map(category => category.name)
          }
        },
      }
    }
  },
}
```

**Other**
When executing `transformEntry` adding an `await` won't break anything for legacy `sync` function. So I guess it's a nice feature to have without any breaking changes.

**Comment by bidoubiwa** [comment]
Oh I did not think bout that. It is a very good idea. 

This should be changed [here](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/server/services/meilisearch/config.js#L55): 

```js
  const transformed = entries.map(entry =>
            contentTypeConfig.transformEntry({
              entry,
              contentType,
            })
          )
```

Into the following:

```js
  const transformed = Promise.all(entries.map( async entry =>
            contentTypeConfig.transformEntry({
              entry,
              contentType,
            })
          ))
```

+ Updating the documentation and tests

The same can be applied to `transformEntry` [here](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/aad2a1e4802808e2b6e0a374fb746881ff4ee242/server/services/meilisearch/config.js#L94)


TODO: 
- [ ] change `transformEntry` to be async compatible (see example above)
- [ ] Update the tests
- [ ] Update the docs
