### ISSUE TITLE
Creating new unpublished content indexes it until the update is re-run

### ISSUE THREAD

**Issue by paulpopus** [meilisearch/strapi-plugin-meilisearch#390]
**Description**
When you create a new item with an initial state of unpublished, it will be indexed until the update hook is ran again to be unindexed.

**Expected behavior**
New items in an unpublished state should not be indexed.

**Current behavior**
New item with an unpublished state is indexed.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/35137243/165076619-c0253f14-0754-488f-9b9b-306e796439e9.png)
^ you can compare the publishedAt states

**Environment (please complete the following information):**
- OS: Linux
- MeiliSearch version: v0.26.1
- strapi-plugin-meilisearch version: latest
- Strapi version: latest

Let me know if more detail is required!

**Comment by paulpopus** [comment]
Yes strapi v4 and this is the transform hook

```js
topic: {
  transformEntry({ entry }) {
    const transformEntry = {
      ...entry,
      id: `${entry.slug}`
    }
    return transformEntry
  },
},
```

**Comment by bidoubiwa** [comment]
The fix should be released this week :)
