### ISSUE TITLE
Collections not loading after plugin install strapi 4.1.8

### ISSUE THREAD

**Issue by Caligulaa** [meilisearch/strapi-plugin-meilisearch#398]
Anyone having issues loading content on the content manager when using the strapi-meili-search plugin? I'm stuck on the loader when try to access the data when that plugin is installed. 

Dev env

Ubuntu 20.04
node 16.13.1
strapi 4.1.8

**Comment by bidoubiwa** [comment]
Hey @Caligulaa I think it is due to a bug reported here #372 The fix is done here #397 It will be released next week.

**Comment by bidoubiwa** [comment]
Hey @Caligulaa normally it should be fixed! Tell me if otherwise

**Comment by Caligulaa** [comment]
Appears to be a-ok. Thank you will be doing quite a bit of testing in the next few weeks will keep you updated if i ran into anything.
