### ISSUE TITLE
Handle many to many to avoid indexing a whole object

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#42]
By making the user only chose one field of the related collection we avoid indexing whole objects

**Comment by harish2704** [comment]
PR #265 addresses this issue I think

**Comment by alfie-bowen** [comment]
@harish2704 I've implemented #265 locally, and although it does affect how an index is stored correctly, when the index item is referred to in a relationship field on another item, the full Strapi object is still indexed.

I think an addition similar to #265 is required which adds a field like "searchIndexRelationshipReferenceField" to the Model object, that enables a single field to be chosen from the content-type to store when adding an index with a relationship field referencing the item.

Here's an example of this issue:
<img width="616" alt="Screenshot 2021-10-06 at 10 12 16" src="https://user-images.githubusercontent.com/65601549/136174444-4467e91f-4923-4e9f-bd1e-3321f5dd0308.png">

I have an index with a list of topics, however they are being stored as objects where we need just the slug.

I'm going to work on a fix for this and will open a PR if it works well

**Comment by bidoubiwa** [comment]
@alfie-bowen thanks a lot! I will be reviewing all the PR's in the coming weeks. Feel free to ask additional questions if needed

**Comment by harish2704** [comment]
@alfie-bowen 

> @harish2704 I've implemented #265 locally, and although it does affect how an index is stored correctly, when the index item is referred to in a relationship field on another item, the full Strapi object is still indexed.

The bug you mentioned is possible.
I didn't taken that case into consideration while sending this PR. ( I was not aware about this case )

Thanks for pointing this out. 

In a quick thinking, a solution came into my mind. I m sharing it here FYI.

**Solution:**

The best place to handle above mentioned case is [`cleanData` function ](https://github.com/harish2704/strapi-plugin-meilisearch/blob/0b7797cbe91e6f6e7617b815721f19c422895e47/lib/utils.js#L35) 

Currently `cleanData` function is implemented in its simplest form, where it check whether a model has `toSearchIndex` or not and if it has, it returns output of `toSearchIndex` function while sending data to indexing. 

This logic is not enough. 

even if `toSearchIndex` is not defined in a model, it should also check its related fields for `toSearchIndex` function and if that is available, it should serialize related fields using `toSearchIndex` function.
