### ISSUE TITLE
Custom populate options per entity

### ISSUE THREAD

**Issue by paulpopus** [meilisearch/strapi-plugin-meilisearch#423]
Related to: https://github.com/meilisearch/strapi-plugin-meilisearch/issues/376#issuecomment-1123932008

**Description**
It'd be very useful to have custom populate options per content/entity type so that we have more control over what data gets indexed and we have access to it in the transform functions.

I imagine a config like this would be fine

```js
ENTITY: {
  settings: {
    ...
    populate: {
      field: '*'
    },
    ...
```

**Basic example**
Sometimes you have more complex data structures with deep nested components and references and you need access to the underlying information or at the very least to have it available in the index.

For example, if you have a single use component field with a component referencing another content type, such as a date period component referencing a timezone, the generic populate: '*' doesn't currently cover the deep nesting required.

This is the patch we've used to add our custom populate for one content type, ideally you can override the `populate: '*'` instead.

```
diff --git a/node_modules/strapi-plugin-meilisearch/server/services/content-types/content-types.js b/node_modules/strapi-plugin-meilisearch/server/services/content-types/content-types.js
index 1e5f6a2..5adf3dd 100644
--- a/node_modules/strapi-plugin-meilisearch/server/services/content-types/content-types.js
+++ b/node_modules/strapi-plugin-meilisearch/server/services/content-types/content-types.js
@@ -142,7 +142,27 @@ module.exports = ({ strapi }) => ({
     limit = 500,
     filters = {},
     sort = {},
-    populate = '*',
+    populate = {
+      programme: {
+        populate: {
+          programme_logo: '*'
+        }
+      },
+      event_type: '*',
+      featured_image: '*',
+      topics: '*',
+      languages: '*',
+      location: {
+        populate: {
+          country: '*',
+        }
+      },
+      dates: {
+        populate: {
+          timezone: '*',
+        }
+      },
+    },
     publicationState,
   }) {
     const contentTypeUid = this.getContentTypeUid({ contentType })
```

**Comment by bidoubiwa** [comment]
Thanks a lot for your suggestion. It is indeed a good idea to add this as a possible setting. At least from what I can see. 

Meanwhile, another possibility would be to populate inside the `transformEntry` function, where you'd be able to fetch your entry with all the options you'd like and add it to the returned entry.

**Comment by paulpopus** [comment]
> Using the [populateEntryRule](https://github.com/meilisearch/strapi-plugin-meilisearch#-populate-entry-rule) setting can do obtain what you want?

Sorry for not replying on this issue, been out on leave...

This setting looks amazing, we'll try it out, thanks for your work.

In the future I'd still like to explore an populate override in the cases where people have prewritten populate objects that they want to re-use across services/plugins.
