### ISSUE TITLE
Missing nested component fields inside another component field

### ISSUE THREAD

**Issue by DrMint** [meilisearch/strapi-plugin-meilisearch#425]
**Description**

Hi, the setup process was straight forward and Meilisearch looks easy to use. However I'm facing a problem with the fields that was sync to Meilisearch. 

Step to recreate:

- Create a collection in Strapi called "collection".
- Create a repeated component named "repeatedcomponent"
- Create a field in that component named "name"
- Create a non-repeated field in that component named "component"
- Create a field in this nested non-repeated component named "title"
- Save, create an entry, add the collection to meilisearch using the plugin
- On the meilisearch dashboard, the entry appears but the nested component fields are missing

Screenshot for illustration, the collection model on the left, the result in meilisearch on the right.

![image](https://user-images.githubusercontent.com/29893320/169661871-82548b9c-6d7c-48e7-b69e-e0517a1aa3df.png)

**Environment (please complete the following information):**
- OS: Debian GNU/Linux
- Meilisearch version: 0.27.1
- strapi-plugin-meilisearch version: 0.6.4
- Browser: Firefox 100
- Strapi version: 4.1.11

**Comment by DrMint** [comment]
Sorry, I've just realized it's probably related to #424

**Comment by bidoubiwa** [comment]
Hey @DrMint I'm currently adding the populate setting in order for you to specify which nested fields you'd like to be fetched as well. :) I'll keep you up to date

**Comment by DrMint** [comment]
Awesome! Thank you for your reply and hard work

**Comment by bidoubiwa** [comment]
Hey @DrMint would you have an example of a `populate` that fetches these nested fields?

**Comment by bidoubiwa** [comment]
Found one!

**Comment by DrMint** [comment]
Hi, sorry I've only been able to check it this afternoon. Unfortunately, I can't seem to be able to do anything with it. 

Here's my package.json
```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "4.1.12",
    "@strapi/strapi": "4.1.12",
    "sqlite3": "5.0.8",
    "strapi-plugin-meilisearch": "^0.6.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "b278e654-01f2-4422-acfa-9a68573dfd02"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

My config/plugins.js (based on the examples in the readme):
```
module.exports = {
  meilisearch: {
    config: {
      "weapon-story": {
        indexName: "nested-weapon-story",
        populateEntryRule: ["stories.translations", "translations"],
      }
    }
  },
}
```

Here's what the content-type is:
![image](https://user-images.githubusercontent.com/29893320/171667754-ead21689-49c2-4213-96ba-03ebf1c1b234.png)

And what I get on Meili dashboard:
![image](https://user-images.githubusercontent.com/29893320/171667845-f08183ce-c44e-41b6-8585-297d918e7d89.png)

I have try uncheck/check/update the collection in the meilisearch plugin page, I've checked that the config file was actually read by changing the `indexName`, I've also tried other populateEntryRule such as:
```
populateEntryRule: ["stories.translations", "translations"]
populateEntryRule: ["stories", "stories.translations"]
populateEntryRule: "*"
```
