### ISSUE TITLE
Hide MeiliSearch master key

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#44]
MasterKey should not be visible on the dashboard. It can only be updated

**Comment by joremysh** [comment]
I would like to work on this.
Do u mean this column should not reveal the API key?
![image](https://user-images.githubusercontent.com/7455516/136052298-75eddf2c-72fb-454e-a2c5-f10dafed439c.png)

**Comment by joremysh** [comment]
> Hello! Yes it should be replaced by asterix, and the back end should not send the information at any time to the front end

the backend API is in meilisearch right? maybe you could open another issue for it.
could you assign the issue to me?

**Comment by joremysh** [comment]
We can do sth like this to toggle password visibility.
https://www.javascripttutorial.net/javascript-dom/javascript-toggle-password-visibility/

> But! When the user comes back to the plugin, the password should not be imported from the backend. Even hided between an input password. Cause a right click on the screen and you have access to the key inside the input. So asterix should be present in the field when the user return to the page but these asterix should hide no password.

We can also set the value to be '****' if msApiKey exists.

**Comment by bidoubiwa** [comment]
Less useful since #191
