### ISSUE TITLE
Update the plugin version compatible with strapi v3 up to date with the latests version of Meilisearch

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#444]
Currently we only maintain the version of this plugin that is compatible with Strapi v4. Nonetheless, a lot of users are still using [the plugin in a Strapi v3](https://github.com/strapi/strapi/tree/v3.6.9) environment. 

As we receive more and more requests for that compatibility we consider maintaining the plugin version compatible with strapi v3. 

We cannot guarantee a deep maintenance on bugs or new features in the v3 version of the plugin but we can guarantee the compatibility with each latest meilisearch version.

We currently still have ~100 users using Strapi v3.

Please upvote this issue if you'd like that compatibility

**Comment by iiiboy** [comment]
If you have carried out this work, then I would be very grateful.

---

```json
"meilisearch:" "0.26.0",
"strapi": "3.6.5"
```

I use `filterableAttributes: ['category.slug']` but it not work in `meilisearch v0.26`. When I used meilisarch 0.27.2 to get back to normal.

**Comment by bidoubiwa** [comment]
Fixed by #542
