### ISSUE TITLE
afterDeleteMany seems to be not implemented yet

### ISSUE THREAD

**Issue by LiquidITGuy** [meilisearch/strapi-plugin-meilisearch#467]
**Description**
When we try to delete many articles from the interface (even only one but selected from the interface) we have the error `Meilisearch could not find an example on how to access the `afterDeleteMany` hook. Please consider making an issue to explain your use case`
 
**Expected behavior**
Deleted entries should be removed from meilisearch too

**Current behavior**
`Meilisearch could not find an example on how to access the `afterDeleteMany` hook. Please consider making an issue to explain your use case`

**Screenshots or Logs**
This feature seems to be not implemented yet 

`server/services/lifecycle/lifecycle.js`
```javascript
        async afterDeleteMany() {
          strapi.log.error(
            `Meilisearch could not find an example on how to access the \`afterDeleteMany\` hook. Please consider making an issue to explain your use case`
          )
        },
```

**Environment (please complete the following information):**
- OS: macos/linux
- Meilisearch v0.28.0 and 0.27.2
- strapi-plugin-meilisearch version: 0.7.0 and 0.6.6
- Strapi version: 4.2.2 and 4.2.3

**Comment by bidoubiwa** [comment]
Hey @LiquidITGuy 

I tried to make `afterDeleteMany` trigger in the past but I never managed to. When I deleted multiple entries they were redirected to `afterDelete`. It may have been added in a recent release of Strapi. Nonetheless, could you show me how you triggered this hook?

**Comment by LiquidITGuy** [comment]
@bidoubiwa thanks for your answer 
it may be added in the last version of strapi maybe
I trigger this hook just by clicking on several checkboxes on a collection and click on delete

`content-manager > my collection > select some entries > Delete`

**Comment by bidoubiwa** [comment]
Thanks @LiquidITGuy I will look into this!

**Comment by bidoubiwa** [comment]
Its released!

**Comment by LiquidITGuy** [comment]
@bidoubiwa thanks for your reactivity.
I tried to upgrade the version 0.7.1 but the bug still remains (not the same way)

the error does not appear in the logs but the index does not seems to be updated.

Tried with strapi 4.2.3, upgrading plugin, 
rebuild strapi
run dev strapi
disable the sync of the entries and re-enable it to remake the index then try multiple delete

<img width="1328" alt="Capture d’écran 2022-07-28 à 18 39 44" src="https://user-images.githubusercontent.com/39310468/181592496-46b860db-219a-40fa-9bd2-2e25b3dbad29.png">
<img width="1301" alt="Capture d’écran 2022-07-28 à 18 40 26" src="https://user-images.githubusercontent.com/39310468/181592502-398b4307-18ef-4807-973e-697b34b370f1.png">

**Comment by bidoubiwa** [comment]
Re-opening

**Comment by bidoubiwa** [comment]
It seems to work for me: 

I deleted 3 entries and it went from 6200 to this: 

<img width="145" alt="Screenshot 2022-08-01 at 12 20 01" src="https://user-images.githubusercontent.com/33010418/182127936-cc467541-b275-40e7-9fa3-15ef8e82486a.png">

How are you deleting the entries?

**Comment by LiquidITGuy** [comment]
@bidoubiwa I select some entries in my collection then click on delete.
I'll try it again tomorrow.

**Comment by LiquidITGuy** [comment]
The 0.7.1 version seems to add some regressions (The unpublish does not remove the index on meilisearch nor the delete one with meilisearch 0.28)
I will open a new issue with more informations

**Comment by bidoubiwa** [comment]
Well, that is very annoying. I don't have time right now to look at it but I will try to work on it asap

**Comment by LiquidITGuy** [comment]
It works very well in the 0.7.1 cf issue [487](https://github.com/meilisearch/strapi-plugin-meilisearch/issues/487) for the explaination of why it does not work on our case
