### ISSUE TITLE
Index not found?

### ISSUE THREAD

**Issue by PaperjetStudios** [meilisearch/strapi-plugin-meilisearch#504]
Hey there,

So I set up meilisearch on my Strapi setup a while ago, and I ticked a model I've got called "Products". This works perfectly, everything about it is good. 

Then now I'm trying to add my "Store" model and it's giving me error: meilisearch: Index `store` not found. error when I click the checkbox on the strapi backend. 

Do you know where I've gone wrong? Or point me in the right direction. 

    "@strapi/strapi": "4.3.4",
    "pg": "8.6.0",
    "strapi-plugin-meilisearch": "^0.6.3"

**Comment by bidoubiwa** [comment]
Hey @PaperjetStudios, is indexing still working with other collections? 
What Meilisearch version are you using (not the plugin but the database)?

**Comment by bidoubiwa** [comment]
Hey @PaperjetStudios is this still an issue?

**Comment by PaperjetStudios** [comment]
Sorry, I ended up reinstalling it all and that seemed to have worked.

<https://paperjetstudios.co.za/>

**Comment by bidoubiwa** [comment]
Perfect! Happy to hear that :)
