### ISSUE TITLE
configure batch size

### ISSUE THREAD

**Issue by LiquidITGuy** [meilisearch/strapi-plugin-meilisearch#536]
**Description**
The batch size is now at 500 content.
When we have a lot of data (more than 10k) it's should be faster to have a bigger amount.

It should be great if we could configure the batch upload number for upgrade in plugin.

**Comment by bidoubiwa** [comment]
Hey @LiquidITGuy 

I'm currently implementing this option! I'll come back to you as soon as it is live :)
