### ISSUE TITLE
feedback status when tasks are running

### ISSUE THREAD

**Issue by LiquidITGuy** [meilisearch/strapi-plugin-meilisearch#537]
**Description**
When we try to update or make the first sync on big amount of data a lot of tasks can be in queued.
Because no feedback are seen, we may check the box many time and juste crash the cloud or make sync append many times.

It should be great to add a feedback about how many indexing operations left and add a warning if too many of them are left before clicking on update

**Basic example**
it can also be usefull when  we use the same meilisearch instance for many indexes

**Comment by bidoubiwa** [comment]
Are you expecting that feedback to be showcased on the dashboard, if yes, any suggestion how? Or in the logs of strapi ?

**Comment by bidoubiwa** [comment]
What about this ? https://github.com/meilisearch/strapi-plugin-meilisearch/pull/539

**Comment by matepaiva** [comment]
I think he is talking about the dashboard feedback. My usecase is somehow related to it.

I have a large collection with a hundred of thousands of entries. When I click it, I have no feedback, but it is even worst: my backend timeouts after 1 minute, so I never receive a feedback.

My suggestion is:
1. As soon as the backend receives the request, it responds successful and it marks it;
2. Start pooling requests to get the status of the models (I think the plugin already does that).

With this approach, we know that the task is running and it is a matter of waiting, and the dashboard is not unresponsive.

**Comment by bidoubiwa** [comment]
Hey @matepaiva 
This seems like a great addition :) I'll let this open for any contributor that might want to work on this as I don't have the time right now. Meanwhile, adding the logs in the back-end might help a bit. 

> As soon as the backend receives the request, it responds successful and it marks it;

Unless I misunderstand, this is already notified no?

> Start pooling requests to get the status of the models (I think the plugin already does that).

It does that yes

> With this approach, we know that the task is running and it is a matter of waiting, and the dashboard is not unresponsive.

the `indexing` column on the dashboard is `true` until the tasks are done.  

But indeed it is hard to see, maybe a spinning icon is better?
