### ISSUE TITLE
Sensitive fields are removed after transforming them

### ISSUE THREAD

**Issue by MarekBodingerBA** [meilisearch/strapi-plugin-meilisearch#553]
Hello,

I've wanted to wrap my data in a new object by transforming it:
```
        transformEntry({ entry }) {
          return {
            type: "article",
            article: {
              ...entry
            },
          };
        },
``` 

When I did that, I noticed that some sensitive fields appeared. After a bit of investigation, I've noticed that sensitive fields are removed after the transformation, not before, which I believe is wrong.

**Comment by bidoubiwa** [comment]
Indeed, thanks a lot Marek! I'm even questioning if this `removeSensitiveFields` method should exist. Maybe some users might want them. Meanwhile, your issue is valid and should be accepted :) I'll flag it as breaking-change in case some users were relying on that information.
