### ISSUE TITLE
Access via API

### ISSUE THREAD

**Issue by matepaiva** [meilisearch/strapi-plugin-meilisearch#561]
**Problem**
Meilisearch a known bug with the size of `data.ms` folder. The only workaround for now is to delete the folder. (https://github.com/meilisearch/product/discussions/517)

**Solution**
I want to make a cron task that: 
1. deletes the folder and 
2. sync again my strapi content with meilisearch using the plugin.

For the 2nd item, I would need the plugin to expose an API so I can request the sync.

**Or...**
Or maybe you know some other strategies to deal with this problem?

Thank you!

**Comment by brunoocasali** [comment]
I answered in the discussion https://github.com/meilisearch/product/discussions/517#discussioncomment-3985854 so maybe we could close it here, unless you have something to add @bidoubiwa :)

**Comment by bidoubiwa** [comment]
Closed as discussion was moved to product repo
