### ISSUE TITLE
My plugin config are not being taken from the plugin.js

### ISSUE THREAD

**Issue by Florian-crg** [meilisearch/strapi-plugin-meilisearch#573]
**Description**
My plugin config are not being taken.

**Expected behavior**

When everything is set on the plugin.js I should not have to add my settings through the STRAPI frontend. Neither access the Setting panel 

**Current behavior**
I have to set my settings in the Setting panel on the STRAPI frontend

**Environment (please complete the following information):**
- OS: macOS  Ventura 13.0
- Meilisearch version: v0.29.1
- strapi-plugin-meilisearch version: v0.8.0
- Browser: Chrome 107.0.5304.110
- Strapi version: 4.4.7

**Comment by bidoubiwa** [comment]
Hey @Florian-crg, not sure I understand! What do you mean with your `settings`?

You credentials can be added in plugin.js here: https://github.com/meilisearch/strapi-plugin-meilisearch#-add-credentials-

**Comment by Florian-crg** [comment]
By settings I mean the stuff that you set in the setting tab. (host and API key)

I did forget on the plugins.js  the to insert my field nested on a `config` object as shown on your README. They were directly on the meilisearch object. 

Sorry for the inconvenience ! And thanks for your answer !
