### ISSUE TITLE
In Strapi Not showing  meilisearch field

### ISSUE THREAD

**Issue by Nish7156** [meilisearch/strapi-plugin-meilisearch#589]
In Strapi Not show  meilisearch field, how can i connect

**Comment by bidoubiwa** [comment]
Hey @Nish7156, i'm not sure I understand what you are asking for. 
Do you want to know what fields are being indexed in Meilisearch? Are your fields not present in Meilisearch?

**Comment by bidoubiwa** [comment]
Hey, Nish, since I don't have any news from you I'm closing this issue. Feel free to re-open it if needed
