### ISSUE TITLE
Attributes not filterable 

### ISSUE THREAD

**Issue by azngeek** [meilisearch/strapi-plugin-meilisearch#631]
**Description**
I have setup Meilisearch using the instasearch plugin using the following configurations:

`
    instantsearch.widgets.refinementList({
        container: "#enabled-list",
        attribute: "gender"
    }),
`
and this is the configuration in strapi

`
module.exports = () => ({
    //...
    meilisearch: {
        config: {
            profile: {
                settings: {
                    filterableAttributes: ['confirmed', 'gender']
                }
            }
        }
    }
})
`

**Expected behavior**

I expect that the attributes 'confirmed' and 'gender' are filterable.

**Current behavior**

Meilisearch tells me that the attributes are not filterable. 

![image](https://user-images.githubusercontent.com/213429/210410064-fae95ed9-e151-4509-b394-3e3b1a411e88.png)

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Debian
- Meilisearch version: 0.30.5
- strapi-plugin-meilisearch version: ^0.8.2
- Browser: Chrome 108
- Strapi version: 4.5.5

![image](https://user-images.githubusercontent.com/213429/210410386-4b18de08-b4e4-4767-a5a6-66f622b13d8c.png)

**Comment by bidoubiwa** [comment]
Hey @azngeek, can I see your Meilisearch plugin configuration in Strapi?

**Comment by azngeek** [comment]
Sure,

it is this one

```
module.exports = () => ({
    //...
    meilisearch: {
        config: {
            profile: {
                settings: {
                    filterableAttributes: ['confirmed', 'gender'], // add categories to filterable attributes.
                }
            }
        }
    }
})
```

**Comment by bidoubiwa** [comment]
I tried it locally and it seems to work for me. 
There are two possible reasons for me you might have this bug:
- Is it possible that your collection is `profiles` and not `profile` ?
- Is it possible that you removed the collection from Meilisearch without restarting your server and then added a document?

Can you check and uncheck `profile` in the Meilisearch dashboard page?

**Comment by azngeek** [comment]
Thanks for the feedback. I got the error. It was because i used a typescript based setup instead of vanilla js. The name of the plugin file must be `plugin.ts` instead of `plugin.js`.

**Comment by bidoubiwa** [comment]
Perfect! Closing this as it seems to be solved :)
