### ISSUE TITLE
Unable to filter

### ISSUE THREAD

**Issue by vlowe85** [meilisearch/strapi-plugin-meilisearch#635]
**Description**
Unable to filter data

Using postman i am doing a PATCH to settings to make `search_terms` filterable
```
    "filterableAttributes": [
      "restricted_to_groups",
      "tags",
      "search_terms"
    ],
```

If i then do a GET on settingsin postman i can see the `filterableAttributes` have been saved ok

Then i clicked `update` on the collection in the strapi plugin dashboard

If i do the GET on settings in postman again i can see that it has lost the `filterableAttributes` i previously set and it is an empty array again.

If i do a search with "filter" like `search_terms='test'` i would expect zero results. But i just get the same results i get without the filter.

It is my understanding that after setting the `filterableAttributes` you must re-index but i am losing the setting on doing so.

**Expected behavior**
When adding filter to query the results will be updated accordingly 

**Current behavior**
No effect adding filter

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- Meilisearch version: v30.5
- strapi-plugin-meilisearch version: v0.8.2
- Strapi version: v4.5.3

**Comment by vlowe85** [comment]
I had the same issue on meilisearch v29, i updated to v30.5 to see if it was any better but same results

**Comment by bidoubiwa** [comment]
Might be similar to #631 

Did you add your settings in the Meilisearch plugin configuration file?

```js
// plugins.js

module.exports = () => ({
    //...
    meilisearch: {
        myCollection: {
            settings: { filterableAttributes: ["restricted_to_groups"]}
       },
    }
})
```

**Comment by bidoubiwa** [comment]
I updated my previous response, it was not formated correctly

**Comment by vlowe85** [comment]
@bidoubiwa no, will try that

**Comment by vlowe85** [comment]
You can close this it works with that plugin config thanks

**Comment by bidoubiwa** [comment]
Nice 🔥
