### ISSUE TITLE
filterEntry on null relation

### ISSUE THREAD

**Issue by vlowe85** [meilisearch/strapi-plugin-meilisearch#636]
Description
How to filter out entries where relationship is null, empty, not set.

I have tried the "filterableAttributes" but have now found you can not filter on `null` 

so i have moved on to try `filterEntry` and added this to the plugin config
```
          filterEntry({ entry }) {
            return entry.restricted_to_groups == null
          },
```

Unfortunatly this imports zero documents from strapi.

`restricted_to_groups` is a Relation field

The use case is that most articles are public accesiible and have an empty restricted_to_groups relation field, if the article has been given a group relation then only that group should see it.

If i cannot filter it via filter once it is in meilisearch it is better that it is not included in meilisearch at all.

Expected behavior
Filter entries with no relation

Current behavior
No entries

Screenshots or Logs
If applicable, add screenshots or logs to help explain your problem.

Environment (please complete the following information):

    Meilisearch version: v30.5
    strapi-plugin-meilisearch version: v0.8.2
    Strapi version: v4.5.3

**Comment by vlowe85** [comment]
I guess entry in `filterEntry` has no relations populated so `entry.restricted_to_groups` is not available

**Comment by bidoubiwa** [comment]
Hey @vlowe85, did you try to add the populate rules in the settings ?

[See example](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/resources/entries-query/populate.js)

**Comment by vlowe85** [comment]
@bidoubiwa no i didnt, looks just what i needed, pls close

**Comment by bidoubiwa** [comment]
Great 🔥
