### ISSUE TITLE
It's not working with strapi? STRAPI COMPATIBILITY Unavailable why it's not Unavailable  ?

### ISSUE THREAD

**Issue by mhmdsalem33** [meilisearch/strapi-plugin-meilisearch#642]
STRAPI COMPATIBILITY
Unavailable
Why not working with strapi ?

**Comment by oluademola** [comment]
Hello @mhmdsalem33,

Sorry for the inconvenience. What version of Meilisearch and Strapi are you running? There is a great chance you're using Strapi v3. We currently provide support with Strapi v3 through[ v0.6.0](https://github.com/meilisearch/strapi-plugin-meilisearch/releases/tag/v0.6.0-strapi-v3.0) of the plugin. Could you please try this and let us know?

Thanks.

**Comment by bidoubiwa** [comment]
Hey @mhmdsalem33, 

As we do not have any news from you, I suppose this is fixed.

If not, please re-open the issue with additional information :)
