### ISSUE TITLE
Plugin error in Strapi 4.4.7

### ISSUE THREAD

**Issue by khang-nd** [meilisearch/strapi-plugin-meilisearch#650]
**Description**
I'm not sure what happened, the plugin used to work with our Strapi project version 4.3.4, but it seems after updating to 4.4.7, it no longer works and throwing the below errors without much of context.
![image](https://user-images.githubusercontent.com/55619201/217155527-cfe7c32e-d666-4e63-8948-81601f22212c.png)

* `Cannot read properties of undefined...` as we open the plugin page and load the collections.
* `Method Not Allowed` as we attempt to select or update a collection type for indexing.

**Environment:**
- OS: Windows 10
- strapi-plugin-meilisearch version: 0.7.1 (updating to the latest 0.9.1 doesn't help)
- Meilisearch version: docker image's latest version
- Strapi version: 4.4.7

**Comment by khang-nd** [comment]
It turns out the error was due to the outdated meilisearch docker image, I needed to pull the new one for it to work again 🤷‍♂️

**Comment by bidoubiwa** [comment]
Thanks for your update! It might help someone with the same issue :)

**Comment by lucasboh** [comment]
I had the same error and pulling the latest image also resolved it. But after that, i got the following error: ` Error: Your database version (0.27.2) is incompatible with your current engine version (1.2.0).` 

To fix that, I had to remove the volume that the meilisearch container was using, as it was created using the old image.
