### ISSUE TITLE
Meilisearch does not show relation's media data

### ISSUE THREAD

**Issue by jeffreytung7** [meilisearch/strapi-plugin-meilisearch#702]
I have a collection called "blog", and in there I have a relation to a "user". This user has a field called "avatar", which is a single image of the user.

But upon checking the "blog" collection in meilisearch after connecting via this plugin, all the fields from "user" are available except "avatar". 

I've tried with multiple collections and relations and it is always the same: any Media data is not included from relations. 

Is this a bug with meilisearch plugin?

**Comment by jeffreytung7** [comment]
Hi, I have noticed this same bug occurs for components as well: any collection with a component inside it that contains Media, meilisearch will not display the Media (but will display everything else from that component). Here's some more info:

Steps to reproduce:

- Create a Strapi collection with a relation to another collection containing media data (e.g., "blog" with a relation to "user" with an "avatar" field).
- Sync the collections to Meilisearch using the Strapi Meilisearch plugin and open Meilisearch dashboard (localhost:7700).
- Observe that the media data (e.g., "avatar") is not included in the related collection within the Meilisearch index (e.g., for the "blog" collection)

Expected behavior:
Media data from related collections should be included in the Meilisearch index after syncing.

Actual behavior:
Media data is not included in the Meilisearch index for related collections.

I would like to know if this is a known issue with the Strapi Meilisearch plugin, and if there is a recommended workaround or fix for this problem. Any assistance or guidance would be greatly appreciated.

**Comment by bidoubiwa** [comment]
Hey @jeffreytung7!
Sorry for the delay I was on holiday. A possible reason for this is that you did not add the populate route in the `entriesQuery`. [See example here](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/resources/entries-query/populate.js).

I should definitely update the readme to help user realise this exists.

Could you tell me if this fixes your issue?

**Comment by jeffreytung7** [comment]
Thanks @bidoubiwa ! That did work, but it also removed some of the fields that were previously visible. For example, in my "blog" collection, before the "image" Media field would be available on meilisearch dashboard, but after adding `populate: ['author.avatar']` the "image" field would no longer be displayed.

Does this mean that using populate will require us to explicitly populate every Media and Component? Ideally I'd like be able to just append a field to populate in addition to the existing fields.

**Comment by bidoubiwa** [comment]
I think it's about mastering the `populate` behavior 😅 I had a hard time understanding how it works. Can you try: 
```
['author', 'author.avatar']
```

There is a way where you obtain the expected result, but I cannot help you more en how populate works :/

**Comment by jeffreytung7** [comment]
@bidoubiwa Thank you for the reply. So the issue is that although `populate: ['author.avatar']` now does make the avatar appear, the fact that we are explicitly using `populate` at all is causing the unintended effect that other components and media is automatically hidden.

For example, say the "blog" collection has 2 fields: 
- an `author` component (that contains `avatar` media file and other fields)
- a `blogCoverImage` media file

The moment we use `populate: ['author.avatar']`, the blogCoverImage which was previously visible on meilisearch is now hidden. 

So we would need to also explicitly state it to `populate: ['author.avatar', 'blogCoverImage']`.

The problem with this is that the project I'm working on may change over time in which content fields being added or removed, and it would hard to manually make sure every populate-able field is added to this array whenever changing the content field structure of a collection. The populate-able fields are things like relations, components, media, and dynamic zones.

Is there an option to just append 'author.avatar' to the list of populate-able fields when calling `entriesQuery`?

I just wanted to ask before I create a custom function to query the content structure of a collection and push to the array

**Comment by jeffreytung7** [comment]
i've solved this issue (of wanting to have populate-able fields including nested components/relations/media be all displayed by default) by doing the following:

1. in `/config/plugins.ts` adding this to my collection `entriesQuery: { populate: '*' },`
2. in `/src/index.ts` in the bootstrap function, grab all the content fields that need to be populated for each collection and add them to the populate array

```
           const meiliPopulate = strapi.plugin('meilisearch').config(collection)?.entriesQuery?.populate;

            if (!meiliPopulate) {
                return; //skip row if entriesQuery.populate doesn't exist
            }

            //since entriesQuery.populate starts off as a string '*', turn it into an empty array first
            if (!Array.isArray(meiliPopulate)) {
                strapi.plugin('meilisearch').config(collection).entriesQuery.populate = [];
            }

            //add the attribute to the populate array
            strapi.plugin('meilisearch').config(collection)?.entriesQuery?.populate.push(attribute);

```
