### ISSUE TITLE
Issue with transformEntry and filterableAttributes

### ISSUE THREAD

**Issue by joelkobjoll** [meilisearch/strapi-plugin-meilisearch#764]
**Description**
I have a city entry with geo data stored in it, I transform it to _geo since I can't store keys that contain underscores in strapi so I transform the value and add a settings object with filterableAttributes: ["_geo"] to enable geoSearch, when ever I add these settings nothing is indexed at all, when I remove it I have no issues what so ever and I can enable the field by a request to meilisearch service, but this isn't really Ideal, ideally I should be able to have this setting in strapi and make the field filterable.

<img width="293" alt="Screenshot 2023-07-11 at 22 52 36" src="https://github.com/meilisearch/strapi-plugin-meilisearch/assets/15344484/d92d1ed6-b7bc-42f8-8f6c-142044fbbaec">

**Expected behavior**
The filterableAttributes setting should not break the indexing of the entity.

**Current behavior**
The filterableAttributes settings is breaking the indexing of the entity.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Ubuntu
- Meilisearch version: 1.2.0
- strapi-plugin-meilisearch version: 0.9.2
- Strapi version: 4.11.4

**Comment by bidoubiwa** [comment]
Thanks for the feedback @joelkobjoll, I raised that to our product team :)

**Comment by Djazz1995** [comment]
@bidoubiwa It also break providing _geo as a `sortableAttributes`

**Comment by bidoubiwa** [comment]
Hey @Djazz1995 and @joelkobjoll, after second thought, this looks like a bug. Could you provide the [task list](https://www.meilisearch.com/docs/reference/api/tasks#get-tasks) and maybe the logs of your backend?
