### ISSUE TITLE
"Method not allowed" when Indexing on Production Mode

### ISSUE THREAD

**Issue by da-kicks-87** [meilisearch/strapi-plugin-meilisearch#771]
**Description**
When trying to add Indexing in Strapi Dasboard on Production mode, i get an "Method not allowed" message and i can't index the content type. Why is this?

Is there an alternative to index the content-types by the `plugin.js` file?

**Expected behavior**
I expect it to allow me to index the content type like on dev mode.

**Screenshots or Logs**
![Screen Shot 2023-07-17 at 11 47 46 AM](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/70115804/101270e5-404a-4a0a-9a70-d40549c54466)

**Environment (please complete the following information):**
- OS: Linux
- Meilisearch version: [v1.2.0]
- strapi-plugin-meilisearch version: [v0.9.2]
- Browser: Chrome 114.0.5735.198
- Strapi version: v4.11.3

**Comment by martin-landhi** [comment]
Did you check the users or admin permissions? That error message maybe have something related with that.

**Comment by da-kicks-87** [comment]
I am Super Admin and it gives me that message.

**Comment by bidoubiwa** [comment]
By front, do you mean the strapi dashboard or another app on which you run your front-end?
Where did you set these credentials? Through the config file or through the `settings` tab in the dashboard Meilisearch plugin's page?

This is definitely a credential issue 😕

**Comment by da-kicks-87** [comment]
Here is errors I get on terminal when i try to index the content-type :

![Screen Shot 2023-07-18 at 3 31 52 PM](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/70115804/95dc2c1a-b5fa-41c7-a0b1-412673e007f3)

**Comment by sanders41** [comment]
> I am using the Master key i got from running the Meiliseach .exe file from my local env. The for the front I reference the public API Key I generated from the /keys route.

Can you expand on this? meilisearch doesn't create the key by default, you need to provide it at startup. And with "local env" is this the same instance you are trying to access now? Because the api key probably won't be the same between 2 instances.

**Comment by da-kicks-87** [comment]
@sanders41  Meilisearch does generate a Master Key if i don't provide one when I run it from the terminal. Thats where I got it from. Once I got it I applied it to it when i got it.  Like this:
`./meilisearch --master-key="EXAMPLE_MASTER_KEY"`

**Comment by da-kicks-87** [comment]
My local installation of Meilliesearch and Strapi work they way they should. 
It's my remote stage env installation of Meilliesearch is where the error occurs. Even if i reference that installation from my local I get the error.

**Comment by sanders41** [comment]
Did you pull the new api key from the remote server or are you using the same one from local? They may not match.

**Comment by martin-landhi** [comment]
On the remote server did you install meilisearch as service?

Follow this to install in production:

https://www.meilisearch.com/docs/learn/cookbooks/running_production

**Comment by sanders41** [comment]
Are you getting the error when using the master key or api key. You are specifically setting the master key so that one will be the same, the api key may not. I would also check @martin-landhi's suggestion on setting up the service.

**Comment by da-kicks-87** [comment]
This is what happens when trying to index content type in Strapi Meilisearch plugin when poniting to stage env installation of Meilisearch. 

![Screen Shot 2023-07-19 at 9 44 25 AM](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/70115804/0c58899f-fe8a-4b68-837b-70ad2b9d0a52)
![Screen Shot 2023-07-19 at 9 44 49 AM](https://github.com/meilisearch/strapi-plugin
![Screen Shot 2023-07-19 at 9 45 01 AM](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/70115804/a0457c25-aaca-4fd7-ac5f-46d1846ec7dd)
-meilisearch/assets/70115804/e9de779a-7f64-4b0e-a1f1-9c30bb97dada)

**Comment by da-kicks-87** [comment]
@sanders41 Error is with the Master Key.

**Comment by sanders41** [comment]
Can you try using curl to see if you get errors that way? If you don't get errors with curl you know it is a problem with the strapi setup, if you still get errors you know the problem is outside of strapi.
