### ISSUE TITLE
Add a setting to allow private fields to be indexed.

### ISSUE THREAD

**Issue by haZya** [meilisearch/strapi-plugin-meilisearch#773]
**Description**
Currently, there is no way to index `private` fields to be used for `search`, `filter`, `sort` or `display`. 

**Basic example**
If I had a field that contains metadata or other value that I do not wish to include in the API responses I would make it a `private` field. However, I still may want to use this value for `search`, `filter` or `sort`. Currently, this is not possible without making the field non-private in which case it requires additional logic on the Strapi side to sanitize the field from the responses.

**Potential solutions**

1. Ignore sanitizing private fields if they appear on either `searchableAttributes`, `distinctAttribute`, `filterableAttributes`, `searchableAttributes` or `sortableAttributes`.

_Pros:_

- Does not deviate from the [Meilisearch settings spec](https://www.meilisearch.com/docs/reference/api/settings).
- Does not introduce an additional setting.

_Cons:_

- By default will be included when using `["*"]` which may not be ideal.
- Prone to be exposed by mistake.

<br/>

2. Add a new setting called `indexedPrivateAttributes` that takes an array of `private` attribute names.

_Pros:_

- Easier to distinguish and less likely to expose sensitive fields by mistake.
- Can work alongside `["*"]` as this is a separate setting.
- Can be more flexible depending on the implementation.

_Cons:_

- By default will allow full scope (`search`, `filter`, `sort`, `display`) unless an additional attribute is added to the same setting to get the `scope`.
- Will deviate from the [Meilisearch settings spec](https://www.meilisearch.com/docs/reference/api/settings).

<br/>

**Other**
PR that introduced the current behaviour: https://github.com/meilisearch/strapi-plugin-meilisearch/pull/703
Mentioned in https://github.com/meilisearch/strapi-plugin-meilisearch/issues/695

**Comment by bidoubiwa** [comment]
Hey @haZya, another solution would be to create a boolean in the settings `noSanitize` that avoid sanitizing any field in any document and then use [`transformEntry`](https://github.com/meilisearch/strapi-plugin-meilisearch#-transform-entries) to filter out what you'd like to keep or not. What do you think?

**Comment by haZya** [comment]
Hi @bidoubiwa Yes, that does sound like a viable solution. I believe this is how it originally worked before the [PR](https://github.com/meilisearch/strapi-plugin-meilisearch/pull/703) that introduced private field sanitization. The difference is the toggle `noSanitize` boolean to set it on or off. 

But the small caveat I see is that this by default will index with full scope `search`, `filter`, `sort`, `display `. And if I only want to say use it for `filter` there is no way to allow only that scope. This is not a major problem, but if there are a lot of private fields or they have a lot of content in them, this could increase the document size making it noticeably slower.

**Comment by brunoocasali** [comment]
Hi @haZya, indeed, it could be an issue, but I believe it will not be a huge concern for 99% of the cases.
If @bidoubiwa's proposed solution can work, I will be glad to review a PR with this :)

**Comment by haZya** [comment]
Hi @brunoocasali 

Yes, I think @bidoubiwa's solution will cover most use cases. I'd like to do a PR on this but my current schedule won't allow me to start working on it immediately. If this is not urgent please go ahead and assign me for this.

**Comment by brunoocasali** [comment]
Nice @haZya no rush then, we can review it whenever you submits it :) 

Thanks a lot for your help!
