### ISSUE TITLE
User authenticated data when search.

### ISSUE THREAD

**Issue by martin-landhi** [meilisearch/strapi-plugin-meilisearch#795]
Hi,

I have an ecommerce mounted in strapi and i use melisearch search engine. I want to allow user to save products in whishlist. How is the best way to return which products are already added to the whishlist of the logged in user when i use the search, in the search results?

Should i process meilisearch results encapsulated in a new strapi API in order to return all the results of meilisearch with the user data inside? or are there a better / high performance way to do this?

![Selection_740](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/101138298/6b485370-8536-423d-9e05-601cf6141814)

**Comment by brunoocasali** [comment]
Hey there,

We are small, so we can't spend much time doing support anymore 😢. You'll have better luck by going to our support channels like Discord, can you please try it first? If you can identify this as a bug, feel free to open up a new issue with a link to the original one, and we'll gladly help you out.

[Discord](https://discord.gg/meilisearch)
[StackOverflow](https://stackoverflow.com/questions/tagged/meilisearch)

Thanks for using Meilisearch!
