### ISSUE TITLE
Missing sortableAttributes functionality

### ISSUE THREAD

**Issue by adwinang** [meilisearch/strapi-plugin-meilisearch#820]
**Description**
I would like to be able to indicate fields as sortable on Meilisearch

**Basic example**
```
settings: {
  sortableAttributes: ["...."]
}
```

**Comment by curquiza** [comment]
Hello @adwinang 

You should already be able to do it: https://github.com/meilisearch/strapi-plugin-meilisearch#-add-meilisearch-settings

Do you get an error?

**Comment by adwinang** [comment]
ah, I just realised a typo. My apologies. Thank you for your help @curquiza !
