### ISSUE TITLE
RBAC access control

### ISSUE THREAD

**Issue by codymorgan** [meilisearch/strapi-plugin-meilisearch#875]
**Description**
it would be very preferable to not show the meilisearch options in the side navigation if the user does not have access to modify the plugins settings. Is it feasible to have roles associated with this plugin so only the users that can view the settings have access to the page at all?

**Basic example**
I've created a user in my installation that has no access privileges using @strapi/plugin-users-permissions, ideally the wouldn't see  the link in the navigation or have access to the page rather than the view in the screenshot

![image](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/1325078/9a6c06f7-c04f-4c3c-910b-bd7931cf142f)

**Comment by mimartinez** [comment]
Hi @codymorgan, I had the same problem and modified the plugin to allow to have permissions on the roles for the plugin.

In the images you can see how now in the roles and in the plugin premises appears the Meilisearch with several options.

I made a PR to upload this functionality that I also missed.

I hope it will help you and solve the role problem.

![Captura de pantalla 2024-03-21 a las 15 57 23](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/888965/a60466b5-28f5-4d6c-a96f-dfca297fed53)

![Captura de pantalla 2024-03-21 a las 15 57 34](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/888965/f7253601-8db1-425f-b002-326e3a962e27)

![Captura de pantalla 2024-03-21 a las 16 02 34](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/888965/1289637c-f12d-4b59-947e-44d50352e278)

![Captura de pantalla 2024-03-21 a las 16 05 16](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/888965/677c9dbb-7bc6-4c30-ac1c-29897473f7e7)

![Captura de pantalla 2024-03-21 a las 16 05 50](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/888965/2856a99d-4ca7-4132-98e3-663694b2672c)

**Comment by codymorgan** [comment]
@mimartinez awesome! i see you opened #892 guess we're just awaiting review then
