### ISSUE TITLE
Hooks are not adding more than 100 documents on afterCreate

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/strapi-plugin-meilisearch#88]
As it appears when adding a huge dataset to MeiliSearch it stops at 100 entries. 
As this is not the expected behavior it is a bug.

```javascript
queue.on('ready', function () {
    queue.process(function (job, done) {
      console.log('processing job ' + job.id);
      console.log('job data page: ', job.data.page);
      const mockCtx = {
        params: { collection: job.data.collection },
        send: (e) => e,
        request: {},
      };
      fetchCollection(mockCtx, { page: job.data.page })
        .then((r) => addCollectionRows(r))
        .catch((e) => console.log('queue error', e));
      console.log('processed job ' + job.data.page);
      setTimeout(function () {
        done(null, job.data.id);
      }, 10);
    });

    console.log('listening for jobs and processing queued jobs...');
  });
};
```

@MANTENN , lets continue here! 

Could you try the following: 
1. Add your documents using the hooks
2. Bug appears! there are only 100 entries. 
3. Using your meilisearch credentials try this route: https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status

It should give back status on your document addition in MeiliSearch.  Could you copy paste it here? 

Also, is there a error thrown in the server logs?

**Comment by MANTENN** [comment]
I created a new branch as requested. Saved the files without a linter. I will just paste the code here considering my linter runs with git hooks will take more time again to make an another repo.

`/config/functions/bootstrap.js`
```
const {
  fetchCollection,
  addCollectionRows,
} = require('../../controllers/meilisearch');

const meilisearch = {
  http: (client) => strapi.plugins.meilisearch.services.http(client),
  client: (credentials) =>
    strapi.plugins.meilisearch.services.client(credentials),
  store: () => strapi.plugins.meilisearch.services.store,
  lifecycles: () => strapi.plugins.meilisearch.services.lifecycles,
};

module.exports = async () => {
  const store = strapi.store({
    environment: strapi.config.environment,
    type: 'plugin',
    name: 'meilisearch_store',
  });
  strapi.plugins.meilisearch.store = store;

  await initHooks(store);

  const Queue = require('bee-queue');
  const queue = new Queue('ingestion', {
    redis: {
      host: '127.0.0.1',
      port: 6379,
      db: 0,
      options: {
        removeOnSuccess: true,
      },
    },
  });

  queue.on('ready', function () {
    queue.process(function (job, done) {
      console.log('processing job ' + job.id);
      console.log('job data page: ', job.data.page);
      const mockCtx = {
        params: { collection: job.data.collection },
        send: (e) => e,
        request: { body: { data: '' } },
      };
      fetchCollection(mockCtx, { page: job.data.page })
        .then((r) => addCollectionRows(r))
        .catch((e) => console.log('queue error', e));
      console.log('processed job ' + job.data.page);
      setTimeout(function () {
        done(null, job.data.id);
      }, 10);
    });

    console.log('listening for jobs and processing queued jobs...');
  });
};
```

`controllers/meilisearch.js`
```
 const Queue = require('bee-queue');
 const queue = new Queue('ingestion', {
   redis: {
     host: '127.0.0.1',
     port: 6379,
     db: 0,
     options: { removeOnSuccess: true },
   },
 });
 
 const meilisearch = {
  http: (client) => strapi.plugins.meilisearch.services.http(client),
  client: (credentials) => strapi.plugins.meilisearch.services.client(credentials),
  store: () => strapi.plugins.meilisearch.services.store,
  lifecycles: () => strapi.plugins.meilisearch.services.lifecycles
}

async function addCollectionRows(ctx) {
  const { collection } = ctx.params;
  const { data } = ctx.request.body;
  const credentials = await getCredentials();
  if (data.length > 0) {
    return meilisearch.http(meilisearch.client(credentials)).addDocuments({
      indexUid: collection,
      data,
    });
  } else {
    return await meilisearch.http(meilisearch.client(credentials)).createIndex({
      indexUid: collection,
    });
  }
}

async function fetchCollection(ctx, options = { page: 0 }) {
  try {
    const { collection } = ctx.params;

    if (!Object.keys(strapi.services).includes(collection)) {
      return { error: true, message: 'Collection not found' };
    }
    const perPage = 100;
    const rows = await strapi.services[collection].find({
      _publicationState: 'preview',
      _limit: perPage, // lock limit to keep the behaviour in case strapi updates this
      _start: options.page * perPage,
    });
    ctx.request.body = { data: rows };
    console.log('procesed', options.page);
    return ctx;
  } catch (e) {
    console.log(`fetchCollection${options ? '(queued):' : ':'}\n`, e);
    return ctx;
  }
}

async function addCollection(ctx) {
  try {
    const recordsCount = await strapi.services[ctx.params.collection].count({
      _publicationState: 'preview',
    });
    // default 100 are returned
    const pages = Math.ceil(recordsCount / 100);
    // page one because the first 100 are inserted below the loop right away
    // the others are queued to not take up too much performance
    for (let page = 1; page < pages; page++) {
      const job = queue.createJob({ collection: ctx.params.collection, page });
      job.save();
      // job.on('succeeded', (result) => {
      //   console.log(`Received result for job ${job.id}: ${result}`);
      // });
    }
    console.log('pages', pages);
  } catch (e) {
    console.log('addCollection:\n', e);
  }
  return addCollectionRows(await fetchCollection(ctx));
}


module.exports = {
  getCredentials: async (ctx) => sendCtx(ctx, getCredentials),
  addCollectionRows: async (ctx) => sendCtx(ctx, addCollectionRows),
  waitForDocumentsToBeIndexed: async (ctx) => sendCtx(ctx, waitForDocumentsToBeIndexed),
  getIndexes: async (ctx) => sendCtx(ctx, getIndexes),
  getCollections: async (ctx) => sendCtx(ctx, getCollections),
  addCollection: async (ctx) => sendCtx(ctx, addCollection),
  addCredentials: async (ctx) => sendCtx(ctx, addCredentials),
  deleteAllIndexes: async (ctx) => sendCtx(ctx, deleteAllIndexes),
  deleteIndex: async (ctx) => sendCtx(ctx, deleteIndex),
  UpdateCollections: async (ctx) => sendCtx(ctx, UpdateCollections),
  reload: async (ctx) => sendCtx(ctx, reload),
  fetchCollection
}

 ```
 
 That's for the queue
 
 
 Without the queue it's still only with 100 records. The reason being is that Strapi model fetches the first 100 documents. 
 
 My code creates pagination and loops through "pages" and queues them with bee-que(backed by redis). I created a video as well of me running the plugin from the master branch without any modifications--may be too long.
 
 https://youtu.be/IyXbypNt7q8

**Comment by MANTENN** [comment]
Just a suggestion. It might be better to build a rust-based ingestion module that would run alongside meilisearch instance this way the implementation would be a lot simpler: a single source of truth(codebase), rest API to ingest, etc.

**Comment by bidoubiwa** [comment]
No jThanks a lot for the detailed explanation.  

I see the issue. That's very limitating. I will make a PR with a fix suggestion. 

Your pagination approach is a very good one! About the queue, MeiliSearch is asynchronous and works with a queue. So it should never take long to receive the response of the add document request. We could send 100 documents per 100 documents batches to MeiliSearch during fetchCollections ( or increase the batch size by iteration on the strapi model)

It is discussed in this pr #60 

To know more about meilisearch queue: https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#async-flow

I hope this is what you were pointing out. Tell me if I missed something!

**Comment by MANTENN** [comment]
@bidoubiwa Yes, I noticed the ingestion is queued with Meilisearch when I first implemented the queue. 

#60 sounds like queuing records 

You still need a queue to fetch records from the database to make sure the plugin isn't taking up too much Strapi resources so it would make sense to just make an ingestion module with Rust lang, Go Lang, etc. whichever would be faster to develop. Hence why I suggested it would make more sense to just build one alongside meilisearch instance and connect it directly to the database.  For CRUD operations webhooks can be utilized in the ingestion engine and you get a single codebase. Not sure whether this has any TCP overhead.

**Comment by bidoubiwa** [comment]
Hello! I see :) This is a good suggestion. Could you maybe make an issue on meilisearch/meilisearch ?  

> You still need a queue to fetch records from the database to make sure the plugin isn't taking up too much Strapi resources

Ah yes, big datasets may suffer from all these fetches! Your suggestion addresses this problem. Until your suggestion is created, we could think about some configuration where you can add some redis credentials and activate the queing of the fetching. 

There is also another solution. You can create a script to add your documents to meilisearch using [`meilisearch-js`](https://github.com/meilisearch/meilisearch-js) for example:

```
const { MeiliSearch } = require('meilisearch')
// Or if you are in a ES environment
import { MeiliSearch } from 'meilisearch'

;(async () => {
  const client = new MeiliSearch({
    host: 'http://127.0.0.1:7700',
    apiKey: 'masterKey',
  })


  // fetch your documents
  let response = await client.index("big_dataset").addDocuments(documents)

  console.log(response) // => { "updateId": 0 }
})()
```

Meanwhile, it should at least work on smaller datasets! Users with a big datasets can still push their documents to meilisearch using a custom script. Using [meilisearch-js] for example. 
```


```

 and
