### ISSUE TITLE
MeiliSearchCommunicationError: fetch failed

### ISSUE THREAD

**Issue by mvaisberg** [meilisearch/strapi-plugin-meilisearch#889]
**Description**
I am using strapi with meilisearch. Strapi is running on aws ec2 with pm2

i an getting sometime this error that down the server completly

2024-03-04T09:33:46: MeiliSearchCommunicationError: fetch failed
2024-03-04T09:33:46:     at Object.fetch (node:internal/deps/undici/undici:11576:11) {
2024-03-04T09:33:46:   errno: undefined,
2024-03-04T09:33:46:   code: undefined
2024-03-04T09:33:46: }
2024-03-04T09:33:46: 
2024-03-04T09:33:46: Node.js v18.18.0

how can i avoid this error or at least avodi the server get down or how can i check more information about why this happend? could have to be with memory ram space? 

**Environment (please complete the following information):**
- OS: ubuntu 18
- Meilisearch version: 1.4..0
- strapi-plugin-meilisearch version:  0.9.2
- Browser: all
- Strapi version: 4.15.4

**Comment by curquiza** [comment]
Hello @mvaisberg 

This error happens when it's impossible for the library to fetch Meilisearch. It's due to an issue about configuration (bad URL)

**Comment by brunoocasali** [comment]
Hi @mvaisberg, can you provide some logs from your running server? Also, can you check what curquiza's mentioned (regarding your configuration).

Since the library seems to be working fine we will need more info in order to be able to help you!

I'll close this issue until then. Thanks a lot!
