### ISSUE TITLE
Can't filter by locale.

### ISSUE THREAD

**Issue by tshmieldev** [meilisearch/strapi-plugin-meilisearch#891]
**Description**
Locale field is not filterable, even if you add it to filterable fields.

**Expected behavior**
You should be able to filter through it normally.

**Current behavior**
You cannot: MeiliSearchApiError: Attribute `locale` is not filterable. Available filterable attributes are: ...

**Screenshots or Logs**
![image](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/58606210/ae20bfe9-7d09-4d64-adfd-46057b29136b)
![image](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/58606210/dcfb3a74-c778-4a93-b0a4-78f3f51a50d8)
![image](https://github.com/meilisearch/strapi-plugin-meilisearch/assets/58606210/cc4c8052-b57d-4978-8411-ef5472170a48)

**Environment (please complete the following information):**
- OS: Docker image of meilisearch, strapi on win10
- Meilisearch version: 1.7
- strapi-plugin-meilisearch version: (newest)
- Browser: Chrome
- Strapi version: (newest)

Why is this an issue?
Because when I add a locale version of an entry it gets added to meilisearch. Then, I have duplicates in search. I don't want that so I want to filter do default locale (that would work for me)

**Comment by curquiza** [comment]
Thanks @tshmieldev for the report, really apprecated

Any PR from anyone is welcome ❤️

**Comment by curquiza** [comment]
Thank you @nitintecg 

@tshmieldev do you still have the error?

**Comment by tshmieldev** [comment]
@curquiza Thank you for mentioning me, I didn't see the proposed solution, it seems promising, I will try it in a few hours

**Comment by brunoocasali** [comment]
I will close this issue, but let me know if you still need some help :)
