### ISSUE TITLE
Support Strapi 5 

### ISSUE THREAD

**Issue by gnodnav** [meilisearch/strapi-plugin-meilisearch#945]
**Description**
As a developer, I would like to see support for the latest version of the Strapi (version 5) in this repository. Strapi 5 was recently released and includes several new features and improvements that would be beneficial for our project.

**Comment by curquiza** [comment]
Hello @gnodnav 
Thank you for the issue
Any PR is welcome from the community ❤️

**Comment by curquiza** [comment]
Replace by https://github.com/meilisearch/strapi-plugin-meilisearch/issues/956

**Comment by TheOuen** [comment]
hi, any updates on this issue?

**Comment by curquiza** [comment]
@TheOuen 
it's done, as you can see in https://github.com/meilisearch/strapi-plugin-meilisearch/issues/956 (cf my message above)
