### ISSUE TITLE
Error: "Authorization header is missing"

### ISSUE THREAD

**Issue by jacobhytter** [meilisearch/strapi-plugin-meilisearch#946]
**Description**
When trying to add a collection to my index i get this error: 
"The Authorization header is missing. It must use the bearer authorization method."
![image](https://github.com/user-attachments/assets/be6fefd1-192b-441e-aa79-eeec19201394)

**Expected behavior**
Uploading the collection.

**Current behavior**
Error message with MEILISEARCH_API_KEY
https://www.meilisearch.com/docs/reference/errors/error_codes#missing_authorization_header

**Environment (please complete the following information):**
- OS:  Docker, Linux
- Meilisearch version: 0.38.0
- strapi-plugin-meilisearch version: 0.12.0
- Browser: Chrome Version 127.0.6533.100
- Strapi version: v4.9.2

**Comment by curquiza** [comment]
Hello @jacobhytter 

Can you let me know which version of Meilisearch you use?
https://www.meilisearch.com/docs/reference/api/version#get-version-of-meilisearch

**Comment by jacobhytter** [comment]
`{ "commitSha": "0df84bbba7db46680e83843dd6454257161a282f", "commitDate": "2024-06-27T12:47:08.000000000Z", "pkgVersion": "1.9.0" }`

**Comment by jacobhytter** [comment]
I have tested to use master-key and public-key and private-key here:
![image](https://github.com/user-attachments/assets/f3503846-e43c-4e00-a9ba-24f7ee551871)

It is populated with the correct api-key.

**Comment by jacobhytter** [comment]
@curquiza any ides? do i need to go down to v1.8.1?

**Comment by jacobhytter** [comment]
I change to 1.8.1 and use the master key as the apikey and now i can push data to the index
