### ISSUE TITLE
Strapi hangs with the following error

### ISSUE THREAD

**Issue by TechWithYou** [meilisearch/strapi-plugin-meilisearch#954]
**Description**
Strapi hangs with the following error and you need to restart the service.

**Expected behavior**
If there is an issue it should fail gracefully.

**Current behavior**
Strapi hangs and is not responding.

**Screenshots or Logs**
0|yarn     |         privateFields.forEach(attr => delete entry[attr])
0|yarn     |                                                    ^
0|yarn     | 
0|yarn     | TypeError: Cannot convert undefined or null to object
0|yarn     |     at /home/ubuntu/fs-strapi/node_modules/strapi-plugin-meilisearch/server/services/meilisearch/config.js:211:52
0|yarn     |     at Array.forEach (<anonymous>)
0|yarn     |     at /home/ubuntu/fs-strapi/node_modules/strapi-plugin-meilisearch/server/services/meilisearch/config.js:211:23
0|yarn     |     at Array.map (<anonymous>)
0|yarn     |     at Object.removeSensitiveFields (/home/ubuntu/fs-strapi/node_modules/strapi-plugin-meilisearch/server/services/meilisearch/config.js:210:22)
0|yarn     |     at sanitizeEntries (/home/ubuntu/fs-strapi/node_modules/strapi-plugin-meilisearch/server/services/meilisearch/connector.js:41:26)
0|yarn     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|yarn     |     at async /home/ubuntu/fs-strapi/node_modules/strapi-plugin-meilisearch/server/services/meilisearch/connector.js:128:27
0|yarn     | 
0|yarn     | Node.js v18.19.1
0|yarn     | error Command failed with exit code 1.

**Environment (please complete the following information):**
- OS:Ubuntu
- Meilisearch version: v1.9.0
- strapi-plugin-meilisearch version: v0.11.1
- Strapi version: v4.24.0

**Comment by brunoocasali** [comment]
Hi @TechWithYou can you try it with Strapi v5 now?!

**Comment by brunoocasali** [comment]
Closing this, since the library evolved to Strapi v5 now. Let me know if this is a mistake and we should reopen!
