### ISSUE TITLE
Strapi 5

### ISSUE THREAD

**Issue by candidosales** [meilisearch/strapi-plugin-meilisearch#956]
I'm trying to use the plugin with Strapi 5 and receive this error during the build:

```bash
  RollupError: [commonjs--resolver] Expression expected in /Users/candidosales/Documents/Projects/turismo-backend-strapi/node_modules/strapi-   
││   plugin-meilisearch/admin/src/components/PluginIcon/index.js                                                                                   
││   file: /Users/candidosales/Documents/Projects/turismo-backend-strapi/node_modules/strapi-plugin-meilisearch/admin/src/components/PluginIcon/   
││   index.js:10:25                                                                                                                                
││   8: import { Search } from '@strapi/icons'                                                                                                     
││   9:                                                                                                                                            
││   10: const PluginIcon = () => <Search />                                                                                                       
││   ^                                                                                                                                             
││   11:                                                                                                                                           
││   12: export default PluginIcon  
```

**Description**
Description of what the bug is about.

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [e.g. v.0.20.0]
- strapi-plugin-meilisearch version: [e.g v0.3.1]
- Browser: [e.g. Chrome version 90.0]
- Strapi version: [e.g. v3.6.2]

**Comment by curquiza** [comment]
Hello @candidosales 

Strapi 5 has just been released, and I'm pretty sure this library does not work with strapi 5 out of the box without doing any change

Any PR are welcome of course!

**Comment by candidosales** [comment]
PR: https://github.com/meilisearch/strapi-plugin-meilisearch/pull/959

**Comment by anshul-fitsib** [comment]
@curquiza @candidosales 

Is there any tentative date for providing a plugin update to support Strapi 5?

**Comment by hoqkhanh** [comment]
Any good news for Strapi 5?

**Comment by curquiza** [comment]
Hello everyone, we are a small team and we cannot work on it 😢

However, we are ready to review any work coming from the community ❤️ 

PRs have been started, but so far none of them we can merge...

Feel free to participate or help at making the work move forward 😊 We thank you for your involvement

**Comment by anshul-fitsib** [comment]
@curquiza 

No one is picking this work in community. Most of the people are unable to migrate from Strapi 4 to Strapi 5 due to this plugin support. 

Is it possible for anyone to pickup this task. This is a humble request

**Comment by anshul-fitsib** [comment]
@curquiza 

Can you please pickup this issue and provide support for Strapi 5?

**Comment by devmanny** [comment]
are you planning to release a strapi-plugin-meilisearch-v5 ?

**Comment by anshul-fitsib** [comment]
Can someone please provide update to Meilisearch plugin to support Strapi 5. It's urgent

**Comment by candidosales** [comment]
@anshul-fitsib it's ready to merge it: https://github.com/meilisearch/strapi-plugin-meilisearch/pull/964

**Comment by brunoocasali** [comment]
Done by @zoran995 and @candidosales #964 🎉

**Comment by brunoocasali** [comment]
@zoran995 can you update the README with the new information regarding Strapi v5?

**Comment by anshul-fitsib** [comment]
Information need to be shared with Strapi team. Still new plugin is not available on Strapi plugin marketplace

**Comment by brunoocasali** [comment]
I've updated the docs myself, but I will be happy to accept a better/complete PR :)

**Comment by brunoocasali** [comment]
Hey @anshul-fitsib check it out now!
