### ISSUE TITLE
Version 0.13.0 has been incorrectly published on npm

### ISSUE THREAD

**Issue by Matb85** [meilisearch/strapi-plugin-meilisearch#980]
**Description**
When I run `npm i strapi-plugin-meilisearch` or `yarn install strapi-plugin-meilisearch` I only get 3 files in my node_modules: `package.json`, `LICENSE` and `README.md`. Also when I go to https://www.npmjs.com/package/strapi-plugin-meilisearch?activeTab=readme I can read that there are only 3 files in the package.

![Screenshot 2024-11-27 at 17 44 10](https://github.com/user-attachments/assets/52b10641-c590-40a8-96a2-901b0c4bf508)
<img width="384" alt="Screenshot 2024-11-27 at 17 48 34" src="https://github.com/user-attachments/assets/2a4ec58e-63c1-4d77-9545-a42b5f9e0be9">

**Expected behavior**
all the necessary files listed in package.json should be downloaded during installation.
![Screenshot 2024-11-27 at 17 47 19](https://github.com/user-attachments/assets/beca7225-c78e-4bc9-a580-96dfc70c5286)

**Current behavior**
When I start strapi the plugin does not show up at all, there are only 3 files strapi-plugin-meilisearch folder in node_modules!

**Screenshots or Logs**
See the screenshots above

**Environment (please complete the following information):**
- OS: Macos 15
- Meilisearch version: 1.3.3
- strapi-plugin-meilisearch version: 0.13.0
- Browser:  Chrome
- Strapi version: 5.4.2

I believe it is just a matter of properly republishing the package.

**Comment by Yordan-Ramchev** [comment]
I can confirm that I have the same issue (v1.3.3)

<img width="305" alt="Screenshot 2024-11-27 at 21 43 12" src="https://github.com/user-attachments/assets/80efbd07-92e5-4989-9d74-0d6f0a9f935e">
